### ISSUE TITLE
Create Admin class for implementation of Admin role

### ISSUE THREAD

**Issue by JRRR0912** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#101]
**Objective**
Create Admin class for use in Role-Based Access Control (RBAC) system.

**Description**
This task involves the creation of Admin role with all its necessary methods to fulfill the desired functions assigned to this role.

**Features:**

- Access student information (view, edit)
- Approve tuition requests
- Reject tuition requests
- Add courses to student schedules
- Remove courses from student schedules
- Manage course catalog
- View and manage academic schedules
- Generate reports (e.g., enrollment statistics, academic performance)

**Time Constraints:**
Create Admin class and exoskeleton of its methods by Thursday, October 10th.

**Completion Criteria:**

- Admin class file: Separate python file for Admin role
- Method definition and documentation: Role functions are defined and well documented.

**Bonus Objective**
All Admin Role functions are available and functional.

**Difficulty:**
5 - Requires creation of a new class with specific methods wanted for this role, although making it functional is not the final objective.

**Priority:**
7 - Sooner completion of this task allows for faster development of project.

**Comment by JRRR0912** [comment]
@Ar2691 @michellebou Please verify issue before proceeding with the task at hand.

**Comment by Carloscaban** [comment]
@michellebou @Ar2691 please assign me to his task

**Comment by JRRR0912** [comment]
![Image](https://github.com/user-attachments/assets/1598fa99-fc7f-4975-ae92-403379d11213)
![Image](https://github.com/user-attachments/assets/7b737acb-8e0d-41dc-97ad-a2b465d38579)
![Image](https://github.com/user-attachments/assets/ffa0b56a-37f9-46c7-a06d-0cc892c71382)

These code fragments (highlighted) were done by @Carloscaban

**Comment by Ar2691** [comment]
@michellebou @RayMuvz
