### ISSUE TITLE
Implement Role Assignment Logic in Login Functionality

### ISSUE THREAD

**Issue by Carloscaban** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#103]
### **Objective:**
Implement a role assignment feature within the login functionality that assigns a single user role based on the login credentials provided by the user. The system should clearly indicate the current role of the user after successful login.

### **Description:**
Develop a mechanism in the login process that assigns roles to users based on their usernames. The system will recognize three roles: Admin, IT Support, and Student, ensuring that only one role can be active at a time. The assigned role should be easily accessible to the user after login.

### **Requirements:**
- Modify the "login" method to invoke the "assign_role" function upon successful login.
- Implement the "assign_role" method to check the username and set the appropriate role flags.
- Ensure that the current role can be retrieved or displayed after login for user confirmation.

**Completion Criteria:**
- User roles are assigned based on username.
- Only one role is active at a time for each user.
- The system correctly identifies and displays the user’s role upon successful login.

**Difficulty: ** 4
**Priority:** 4

Assignees: @Carloscaban @JRRR0912

**Comment by JRRR0912** [comment]
![role fetch 2](https://github.com/user-attachments/assets/5694a925-cb2c-4ee4-a9a8-2b26234aabf1)
![Role fetch](https://github.com/user-attachments/assets/4c69b91e-a9e5-45e5-9b1c-ef41faab4661)

Code fragments that should make the role appear after a successful login.
