### ISSUE TITLE
Create Database Schema

### ISSUE THREAD

**Issue by nelson-escalona** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#11]
Objective: Create efficient database design so that database can be created for the apps testing.
Description: We will be creating a database design(tables, relations, etc) using a relational model in dbdiagram.io. Once the design is finished, an SQL file of the database can be downloaded. The database can be created with that file.
Implementation plan: The plan in to create the design, download the SQL file and use that file to create the tables in the database.
Deadline: Friday, Sept. 6.
Difficulty: 6
Priority: 8

**Comment by nelson-escalona** [comment]
@michellebou @Ar2691 . Issue has been approve by the managers. Issue is currently in "waiting for developers" state. The assignees for this task would be @carlospepin23 and myself (@nelson-escalona ). Let me know if you need any other info on my part.

**Comment by Yamil-Serrano** [comment]
Backend Developer here, if you need my assistance during the database design process, or its documentation, I am willing to lend a hand.

**Comment by nelson-escalona** [comment]
@michellebou @Ar2691 
![image](https://github.com/user-attachments/assets/09233939-d7cc-42f2-ba9e-b5c8ba3cf519)
This is the design we came up with. As you can see, we have created a student table for personal information and a couple of other tables that are related to each other in a way that we can add courses and simulate course enrollment. 

We are able to edit this scheme so let me know if you have any ideas for changes and/or additions to the scheme.

**Comment by Ar2691** [comment]
Add the key icon to course_code in table sections.
