### ISSUE TITLE
Research PyQt5 for College Planning Feature Implementation

### ISSUE THREAD

**Issue by J3SSY-ANDU** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#114]
Objective:
Conduct research on how to implement the "College Planning" feature using PyQt5 to ensure consistency with the rest of the application's interface.

Description:
This task involves researching how to effectively use PyQt5 to implement the "College Planning" feature. The feature will allow users to plan their courses for each semester, select available courses, and view completed courses. The research will focus on how to structure the UI components within PyQt5, such as grids, tables, and buttons, as well as any necessary event handling and state management for this specific feature.

Features:

Creating the Semester Planner
Research how to create a grid or table layout using PyQt5 that represents semesters and allows users to input or modify their planned courses.

Course Selection Mechanisms
Investigate PyQt5 widgets such as buttons and list views to create the "Available Courses" and "Courses Taken" sections. These sections need to support adding and removing courses.

Interactivity and Event Handling
Look into how to handle user interactions in PyQt5, such as clicking buttons to move courses between lists, selecting courses, and saving changes to the semester planner.

Integrating Dropdown Menus and Dynamic Input
Explore how to implement dropdown menus or combo boxes for course selection and how to dynamically update course lists based on prerequisites or other factors.

Styling and Layout Consistency
Ensure that the design and layout of the "College Planning" feature are consistent with the rest of the app by researching styling options in PyQt5, including widget customization and alignment.

Expected Outcome:
The research should provide detailed steps and documentation on how to implement the "College Planning" feature using PyQt5, including code snippets for creating the semester planner layout, handling course selection, and managing user interactions.

Difficulty:
3 (Focused on researching how to apply existing knowledge of PyQt5 for this specific feature.)

Priority:
5 (Needed to ensure the "College Planning" feature is implemented consistently with the rest of the application.)

**Comment by J3SSY-ANDU** [comment]
For the **College Planning** feature, we will adopt a hybrid approach by using **QtDesigner** for the UI layout and **PyQt5** for handling interactivity and backend integration. This method will streamline both the design and functionality of the feature, ensuring efficiency and consistency across the application.

### QtDesigner:
- **QtDesigner** is a powerful tool for visually designing the user interface using a drag-and-drop approach. It allows us to build the UI components like grids, tables, buttons, and dropdowns without writing code for the layout, which accelerates development.
- With **QtDesigner**, we will create the semester planner, consisting of a grid or table structure for course planning (using `QTableWidget`), course selection lists (`QListWidget`), and interaction buttons (`QPushButton`). 
- After designing the interface, QtDesigner generates `.ui` files, which can be loaded into the application via PyQt5. This ensures a consistent look and feel throughout the app, since UI elements will follow a uniform design across the whole system.

### PyQt5:
- **PyQt5** is a Python library that provides the tools to build desktop applications with the Qt framework. We will use PyQt5 to manage interactivity, such as handling user inputs, managing the course planning process, and integrating the UI with backend logic.
- For example, in PyQt5, we will connect UI components (created in QtDesigner) to functions that handle course selection, adding and removing courses from semesters, and saving user data. This is done through PyQt5's signals and slots system, which facilitates communication between the UI and backend.
- PyQt5 will also manage dynamic behaviors like updating the list of available courses based on user input (e.g., prerequisites or completed courses).

### Benefits of This Approach:
1. **Separation of Concerns**: Using **QtDesigner** for UI and **PyQt5** for backend logic keeps the interface design separate from the logic, improving maintainability.
2. **Visual UI Design**: **QtDesigner** provides a visual approach to building the interface, reducing design complexity and ensuring consistency across the application.
3. **Efficient Development**: By using **QtDesigner** for the layout and PyQt5 for event handling and state management, we streamline the development process, making it faster to create and maintain the feature.
4. **Flexible Interactivity**: **PyQt5** allows us to easily manage user interactions, such as moving courses between lists, selecting semesters, and saving changes, while also enabling dynamic updates to the UI based on user actions.

### Workflow:
1. **Design the UI in QtDesigner**: We will use **QtDesigner** to create the semester planner's layout, including tables, course selection lists, buttons, and other interface elements. This will ensure the layout is visually consistent with the rest of the application.
2. **Load the UI in PyQt5**: The `.ui` files generated by **QtDesigner** will be loaded into the application using PyQt5. This keeps the UI and logic separate.
3. **Backend Integration with PyQt5**: In PyQt5, we will connect the UI components to the application’s backend, handling user events like course selection, course moves between lists, and data saving, all using PyQt5's event handling system.

This combination of **QtDesigner** and **PyQt5** ensures that we can build a feature-rich, user-friendly **College Planning** tool that integrates seamlessly with the rest of the application.

**Comment by nelson-escalona** [comment]
LGTM 👍

**Comment by PedroRodz** [comment]
@Ar2691 @michellebou
