### ISSUE TITLE
Create UI for Available Courses Section in College Planning Feature

### ISSUE THREAD

**Issue by J3SSY-ANDU** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#116]
Objective:
Design and implement the UI layout for the Available Courses section in the "College Planning" feature.

Description:
This task involves creating the static user interface for the Available Courses section, where users will eventually view a list of available courses for each semester. The UI should include space for displaying course details such as course name, credits, prerequisites, and a button for adding the course to the semester planner. The design should follow the overall application style but will not include any course selection or interaction functionality at this stage.

Features:

Courses List Layout
Create a vertical list layout for displaying available courses. Each course entry should be visually separated and include placeholders for course details such as the course name, number of credits, prerequisites, and suggested semester.

Course Information Display
Implement text fields for each course to display essential information, including course name, prerequisites, credits, and a color indicator (green for eligible courses, red for unavailable courses based on prerequisites).

Add Course Button
Add a static "+" button next to each course entry to indicate where users will eventually be able to add courses to their semester planner. The button should be non-functional for now but clearly visible as part of the UI.

Styling and Formatting
Ensure the layout and styling of the Available Courses section is consistent with the rest of the app, including colors, borders, and fonts, as per the design provided.

Expected Outcome:
The static UI for the Available Courses section will be implemented, displaying a list of courses along with relevant course information and a non-functional "+" button for future interactivity. The layout should match the design but will remain non-interactive for now.

Difficulty:
3 (Mainly focused on UI design without interaction logic.)

Priority:
4 (Important for building the visual structure of the "College Planning" feature.)

**Comment by PedroRodz** [comment]
![Screenshot (2)](https://github.com/user-attachments/assets/c910cfb3-091d-4cde-b386-45182e38c0bd)
I designed the ui on qtDesigner which is a tool that lets you make your design into a .py file.
Jessy and I collaborated using pair programming for this task. The commit will be done by Jessy.

**Comment by J3SSY-ANDU** [comment]
<img width="1153" alt="Screenshot 2024-10-24 at 8 30 30 PM" src="https://github.com/user-attachments/assets/b43754a1-52ff-40e8-aae4-bf4dbd8103be">

**Comment by nelson-escalona** [comment]
LGTM👍

**Comment by PedroRodz** [comment]
@Ar2691 @michellebou
