### ISSUE TITLE
Create UI for Courses Taken Section in College Planning Feature

### ISSUE THREAD

**Issue by J3SSY-ANDU** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#117]
Objective:
Design and implement the UI layout for the Courses Taken section in the "College Planning" feature.

Description:
This task involves creating the static user interface for the Courses Taken section. The UI will display the list of courses the user has completed, along with information such as course name, credits, grade, and any relevant details. The design should follow the overall app style but will not include any functionality at this stage, such as editing or removing courses.

Features:

List Layout for Completed Courses
Create a vertical list layout for displaying courses the user has completed. Each course entry should include placeholders for details such as course name, credits, grade, and any additional information (like unlocked courses).

Course Information Display
Implement text fields to display relevant course information: course name, credits, grade received, and semester in which the course was taken.

Static "+" Button
Add a static "+" button next to each course for future functionality. The button will be non-functional for now but should be included in the design for consistency.

Styling and Formatting
Ensure the design and layout of the Courses Taken section match the app's overall visual style, including the colors, borders, and typography in line with the provided design.

Expected Outcome:
The static UI for the Courses Taken section will be implemented, showing a list of completed courses along with placeholders for course details and a static "+" button for future use. The section will match the overall design but will not have any interactive functionality for now.

Difficulty:
3 (Focus on creating the visual layout without interactive logic.)

Priority:
4 (Important for building the visual structure of the "College Planning" feature.)

**Comment by PedroRodz** [comment]
![Screenshot (2)](https://github.com/user-attachments/assets/c910cfb3-091d-4cde-b386-45182e38c0bd)
I designed the ui on qtDesigner which is a tool that lets you make your design into a .py file.
Jessy and I collaborated using pair programming for this task. The commit will be done by Jessy. This part of the design will be changed for now and consolidated into one table.

**Comment by J3SSY-ANDU** [comment]
![Uploading Screenshot 2024-10-24 at 8.30.30 PM.png…]()

**Comment by J3SSY-ANDU** [comment]
<img width="1153" alt="Screenshot 2024-10-24 at 8 30 30 PM" src="https://github.com/user-attachments/assets/a1e34a93-fda4-4949-aad8-6137d253fc77">

**Comment by nelson-escalona** [comment]
LGTM👍

**Comment by PedroRodz** [comment]
@Ar2691 @michellebou
