### ISSUE TITLE
[Lecture Topic Task] Developing diagrams about the components of this application.

### ISSUE THREAD

**Issue by cristianMarcial** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#120]
Objective: 
Create sequence or statecharts diagrams that represents the general structure of different facets of the application.

Description: 
Two or more sequence diagrams will be created that show:
- the structure of the modules in the directories and their functionalities with respect to them
- diagram(s) showing the relationship of the hierarchy between the database and the requester (user)

Requirements:
- Have at least two diagrams that show the info stipulated in the description in a readable image format.

Time Constrains:
Before October 23

Completion Criteria:
Have all the information listed in the requirements section.

Difficulty:
4

Priority:
3, although it is not so important, the diagrams can help us to better understand how our project works.

**Comment by Yamil-Serrano** [comment]
I am currently developing diagrams to illustrate the components of this application. Please take a look and let me know if there are any modifications needed or if anything is unclear. I'm open to suggestions for improvements.

![image](https://github.com/user-attachments/assets/04736855-e912-4bc1-a80d-bd2ebcff957b)

**Comment by cristianMarcial** [comment]
Made the seq diagram more accurate in terms of the app module layout 
![Uploading Login_seq-2024-10-25-011553.png…]()

**Comment by cristianMarcial** [comment]
![Login_seq-2024-10-25-011553](https://github.com/user-attachments/assets/88920598-f3b2-41aa-b9b3-bbad0ce7145a)

**Comment by cristianMarcial** [comment]
statechart about behaviors between modules 
![login_statechart-2024-10-25-045233](https://github.com/user-attachments/assets/b80b01a5-9811-41ef-9eca-de20f13c2528)

**Comment by cristianMarcial** [comment]
The last two diagrams are the ones which are being used by the documentation. This task can be considered as complete.
