### ISSUE TITLE
Define Privileges for Roles: Admin and Student

### ISSUE THREAD

**Issue by Yamil-Serrano** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#121]
**Objective:**
Create a visual mapping that defines the privileges for the Admin and Student roles in the Role-Based Access Control (RBAC) system using a graph-based representation.

**Description:**
This task involves creating a clear, visual mapping for the Admin and Student roles in the RBAC system to define their respective access rights. The Admin role will have full access to manage student accounts and schedules, while the Student role will have limited access to course enrollment and personal profile management. The mapping will be created using a diagram (similar to the provided example in Mermaid format) to easily visualize and implement the role privileges.

**Roles and Privileges Mapping:**

 **Admin:**
- Can manage student accounts (create, edit, delete).
- Can manage students' course enrollment and academic schedules.

**Student:**
- Can view available courses.
- Can enroll in available courses.
- Can view their personal profile and enrolled courses.

**Features:**
Privileges Mapping Definition:
Create a graph-based mapping that defines the Admin and Student roles and their respective permissions.

**Requirements:**
Graph-Based Mapping:
Create a visual mapping using a graph format (as in the provided Mermaid example) that shows the privileges for Admin and Student roles.

**Time Constraints:**
Complete the visual mapping and implementation by Monday, Oct. 21.

**Completion Criteria:**
A graph-based privileges mapping is created and implemented for Admin and Student roles.

**Difficulty:**
4 (Requires creating and enforcing a visual role mapping).

**Priority:**
8 (Important for system security and user role management).

**Comment by Yamil-Serrano** [comment]
I have made a diagram of some privileges of the Student and Admin roles @Ar2691 @RayMuvz @JRRR0912. Please tell me if you think I should add or remove privileges. I attach the [link](https://mermaid.live/edit#pako:eNptksluwjAQhl_FmnNAEAeyHCqxVV2EVJWqhyYcTDwEq4mNHLstRbx73QRQaevDaGb-bxbL3kOuOEIChWbbDXmaZpK4M0ofVYn1knQ6V2Scjngl5PIoNblJujCWozTHbGvHjTZN50yyAskRqckoz5V1zvInNvuDTZTVNdaESU4W-Qa5LfGi5DqdSa3KktSnEiGJVLLDsdCIJD82UPrsmg0zhCtHGbLCUsmCGOWyKBxjtRa5LW11cYtJM-smfRb4ftpp-VO6Pa3hpo_eBFuV-C9317Z40GotzjdppftWavsg_1XeWPCgQl0xwd3z7L9TGbi9K8wgcS5n-jWDTB4cx6xRi53MITHaogda2WIDyZqVtYvsljODU8HcG1cnZMvki1LVGXIxJHv4gCToDuggpHHg94dR5AcDD3aQ-EHQDeMhDWhIB1GP0oMHn02DXjcOw144jP0ojqI-7VEPkAuj9Lz9Ws0PO3wB4zO_6A) to the diagram editor and the reference image:
![Screenshot 2024-10-19 200948](https://github.com/user-attachments/assets/c7368de7-baa5-4418-b37b-aaec0b8100e1)

**Comment by JRRR0912** [comment]
Hello @Yamil-Serrano, 

The diagram looks just fine. I believe the roles are clear with their privileges. I will only make note of a small typing mistake in the Student section. One of the privileges says "Enroll in Aviable Courses". Other than that, I believe it is all good. Although, I may suggest a rewrite in the third point in the Admin section. 

"Enroll students in courses that are not in their curriculum and may bypass course size via overfill" 

This to avoid a bit of redundancy and to add the overfill (sobrecupo) feature.

**Comment by Yamil-Serrano** [comment]
Thanks for the recommendation @JRRR0912, I already fixed the type and redundancy in the admin role.
![image](https://github.com/user-attachments/assets/28c45dd0-ca3d-42bc-8518-984554b6568e)

**Comment by Yamil-Serrano** [comment]
@Ar2691 @RayMuvz tell me if you think I should add or remove privileges, if you think it is enough then we can proceed with the procedure of closing the task.

**Comment by Ar2691** [comment]
@michellebou
