### ISSUE TITLE
Modify the code made for the sections catalog exporter to export courses

### ISSUE THREAD

**Issue by cristianMarcial** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#122]
**Objective:**
Once the information from the sections catalog has been exported to the database, the sections exporter will be modified so that it can upload courses.

**Description:**
Modify the code inside the "_export.py_" module on the "_scrapped_curriculum_" directory so that instead of using the CRUD functions for sections, the functions for courses in the database are used.

**Requirements:**
- that when running the module, the database has a course catalog with some courses from this semester.

**Time Constrains:**
Before October 23.

**Completion Criteria:**
Everything listed in the requirements section is completed.

**Difficulty:**
2; although knowledge of the operation of the modules with the CRUD functions and the structure of the Database is required, if the previous exporter is already set, it's not so difficult doing this.

Priority:
5, we need to have some course catalog already present on the database.

Suggested Assignees: 
Chese157 and JorgeGuzman1

**Comment by cristianMarcial** [comment]
It works
![Screenshot (1068)](https://github.com/user-attachments/assets/bf8a5437-e838-447e-830c-fa1f20a647a9)

**Comment by michellebou** [comment]
@Ar2691
