### ISSUE TITLE
[Lecture Topic Task] Algebras, use of Diagrams in the project

### ISSUE THREAD

**Issue by Gian-Go** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#127]
Objective:
Make additions on the documentation relative to project diagrams

Description:
The project uses diagrams to complement some descriptions or explanations in a way such that the text clarifies the diagram, and the diagram clarifies the text. The diagrams are used according to the purposes of the type of diagram. For example, sequence diagrams were developed for features such as the College Planning feature to better explain the relationships between the user, the UI and the backend/database. 

Requirements:
Add the diagrams to the documentation coupled with an explanation to help readers understand the entity relationships found within the project.

Completion Criteria:
Any additions and changes follow the guidelines already established for the milestone 1 submission.

Time Constraints:
October 25

Difficulty:
4

Priority:
6

Suggested Assignees:
2

**Comment by keisanabria** [comment]
Added https://github.com/uprm-inso4101-2024-2025-s1/semester-project-regiupr/issues/123's diagram to the documentation.

**Comment by keisanabria** [comment]
Added #89 and #120 's diagrams to the documentation (all the past diagrams have been added to section 2.3.1 of the Documentation document)

**Comment by keisanabria** [comment]
Falta #130 's diagram.

**Comment by keisanabria** [comment]
Finished adding #130.

**Comment by keisanabria** [comment]
![image](https://github.com/user-attachments/assets/c1210cdd-e984-444a-9109-687a07bb9383)
Figure 1: Database Schema for data faculties
The database design follows the table system showcased above, with each table consisting of key data faculties: students, students_courses, course, course_planning, course prerequisite, program_faculty, sections, curriculum, curriculum courses, student_curriculum, semester_planning. This database schema helps to keep organization by connecting curriculum to classes and students, helping to keep track of the courses selected by a student to the specific faculty enrolled and record of the classes taken. Semester planning course and planned course table helps at the time of class enrollment to identify with ease the class to be taken. Each of these are prepared separately such that each may be modified independently while maintaining the capabilities to communicate with each other thanks to mysql.connector. For example, the students.py file in particular handles the student_id variable that is required (but not modified) by the student_courses.py file. This way, all files handle key data specific to their category, allowing for easier management and storage of said data. The database is hosted on an AWS EC2 instance thanks to its wide range of functionalities for most, if not all, database purposes while also offering robust cloud security features. This allows for versatility and ease of modulation for future tasks, without risk of data leaks.

![image](https://github.com/user-attachments/assets/ae4f7378-05ad-40f0-95e0-50029565174f)


Figure 2: Role-Based Access Control (RBAC) System for Tuition Application  
This diagram provides a visual representation of the roles and their associated privileges within the Role-Based Access Control (RBAC) system of the tuition application. It illustrates the hierarchical structure of roles such as Student, Admin, and IT Support, as well as the corresponding privileges assigned to each. The diagram maps out actions like profile management, course enrollment, system settings access, and technical troubleshooting, offering a clear overview of how responsibilities and privileges are distributed across the system. This serves as a reference for developers to implement and manage access control efficiently.

![image](https://github.com/user-attachments/assets/603e26c0-a9fc-49af-ab89-5719e1a40d03)
![image](https://github.com/user-attachments/assets/64d15ac4-69d1-4b04-b1d1-77822273b8b2)


Figure 3 and 4 (respectively): Sequence and Statechart Diagrams Representing Application Facets  
This diagram set provides a visual representation of key structures within the application. The first diagram illustrates the modules in the directory structure, highlighting the functionalities tied to each module and their interactions. The second diagram displays the relationship between the database and the user (requester), detailing the hierarchy of data retrieval, processing, and response delivery. These diagrams offer a clear view of the architectural setup, helping to better understand the internal workings and module interdependencies within the project.

![image](https://github.com/user-attachments/assets/21b4e015-fd09-4b52-90e7-ce93b7fa5817)

Figure 5: Sequence Diagram for the College Planning Feature  
This diagram illustrates the interaction flow between the user, the user interface (UI), and the backend/database for the College Planning Feature. It outlines each step in the process, from user input to the actions taken by the UI and the requests sent to and responses received from the backend/database. The sequence of operations shows how data is fetched, processed, and displayed, ensuring that the user's college planning actions are accurately supported by the system’s architecture.

![image](https://github.com/user-attachments/assets/3db27d5e-9427-487a-94a9-bc4a265b74e8)

Figure 6: Sequence Diagram for Profile Actions  
This diagram illustrates the interaction flow between the user, the Profile UI, and the backend during profile actions within the tuition application. It details the steps taken when a user views and updates their profile information, including email and password. The sequence diagram outlines the process of loading profile data from the backend, enabling the user to edit their information, saving the changes, and confirming successful updates. The diagram clarifies how these actions are managed across the system, ensuring smooth profile management for users.
