### ISSUE TITLE
[Lecture Topic Task] Sprints and Implementation logs

### ISSUE THREAD

**Issue by Gian-Go** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#128]
Objective:
Make improvements on the documentation relative to Implementation and sprint logs.

Description:
It is necessary to add any missing implementation information into the document, while also logging all the accomplishments during the milestone, divided within their respective sprints. 

Requirements:
Changes and additions must follow the guidelines already established for the milestone 1 submission.

Completion Criteria:
• The logbook gives an overview of the changes (but not the full changed content) since the last submission.
• The actual changes, new developments and such are integrated into the overall document.

Time Constraints:
October 25

Difficulty:
4

Priority:
6

Suggested Assignees:
2

**Comment by saul108** [comment]
https://docs.google.com/document/d/1WvPumtALrkqYM8bgXZRwuFdoEh5l9ka6etdCJM-uFX8/edit?tab=t.0
![image](https://github.com/user-attachments/assets/1c9c4faf-ea7d-4edc-9f64-8300754b2e15)
![image](https://github.com/user-attachments/assets/7e523e58-5349-471f-b290-e7f695e65332)
![image](https://github.com/user-attachments/assets/4676207e-54a3-4110-8a28-a3b335ce0749)


Added relevant tasks on sprint log books and implementation.
