### ISSUE TITLE
Merge both courses tables to one table.

### ISSUE THREAD

**Issue by nelson-escalona** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#148]
Objective:
The objective here is to change the current design to have only one table instead of two. 

Description:
During the end of the last milestone, we realized that it would be better to have only one table for courses and to have the courses color coded. The scope for this issue is to display all courses in one table.

Expected Outcome:
For this issue, the expected outcome is to have only one table displaying all courses. Color coding is NOT in the scope of this task.

Difficulty:
3

Priority:
5

Assignee:
@J3SSY-ANDU

**Comment by J3SSY-ANDU** [comment]
<img width="1208" alt="Screenshot 2024-11-12 at 12 00 04 AM" src="https://github.com/user-attachments/assets/695d16ae-27ee-4d67-a434-7ddd0690cec6">
Deleted the passed courses table and created the courses color coded. Red for the failed courses, yellow for the ongoing courses, and green for all the courses that are available for enrollment that are not classified in red or yellow.

**Comment by nelson-escalona** [comment]
LGTM👍🏼
