### ISSUE TITLE
Add color coding to courses in the table.

### ISSUE THREAD

**Issue by nelson-escalona** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#149]
Objective:
The objective here is to sucessfully color code the courses.

Description:
For this issue, we want to color code courses, identifying in **green** the courses that the student has not taken and in **light blue** the courses that the student has already taken. These colors are subject to change and suggestions will be taken into consideration.

**IMPORTANT NOTE** This issue is to be completed/worked on **after** issue #148. 

Expected Outcome:
Courses should be visually color coded in the courses table.

Difficulty:
3

Priority:
4

Assignee:
Same developer from issue #148.

**Comment by J3SSY-ANDU** [comment]
<img width="1352" alt="Screenshot 2024-11-25 at 12 07 21 PM" src="https://github.com/user-attachments/assets/3cc9c864-8a8e-447c-9d3c-5a24caff78cb">
Color code courses using green for available courses, blue for passed courses and red for failed courses.

**Comment by nelson-escalona** [comment]
LGTM👍
