### ISSUE TITLE
Add College Planning button to sidebar of application.

### ISSUE THREAD

**Issue by nelson-escalona** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#150]
Objective:
The objective of this issue is to fully implement the College planning button in the RegiUPR application.

Description:
For this issue, we want to implement a button that says "College Planning" in the side bar of the RegiUPR application, so that when the user presses the button, the College Planning feature appears.

IMPORTANT NOTE This issue embarks both the front end aspect of the button and the back end of the button.

Expected Outcome:
The button in the sidebar must be **FULLY** functional. Meaning that the button must be visually good and fully working.

Difficulty:
4

Priority:
5

Assignee:
@J3SSY-ANDU

**Comment by J3SSY-ANDU** [comment]
<img width="1352" alt="Screenshot 2024-11-25 at 12 07 21 PM" src="https://github.com/user-attachments/assets/2fcfd842-11e2-48cb-ac0e-ea597492d017">
Added the College Planning button to the main menu.

**Comment by nelson-escalona** [comment]
LGTM👍 Changes were merged into the main college planning branch.
