### ISSUE TITLE
Add GPA and Credits columns to the database.

### ISSUE THREAD

**Issue by nelson-escalona** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#151]
## Objective:
Update the database schema to include GPA and Credits columns for curriculum tracking.

## Description:
This task involves updating the database to include new columns for tracking GPA and credits. Specifically, we need to add the following columns:

**General GPA:** To store the overall GPA of the student.
**Specialty GPA:** To store the GPA for the student's chosen specialty or major.
**Completed Credits:** To track the number of credits the student has already completed toward their degree.
**Total Credits:** To specify the total number of credits required to complete the curriculum.

The goal is to integrate these new columns into the existing schema without disrupting the overall database structure. Calculations for remaining credits will be derived dynamically based on the completed and total credits.

## Completion Criteria:
Once the new columns are added to the schema, the updated database design will be exported into a .sql file for integration into the live database.

## Time Constraints:
Complete by **Monday, November 11th**.

### Difficulty:
2

### Priority:
5

## Assignee:
@carlospepin23

**Comment by carlospepin23** [comment]
# Database Schema Update Report

This database schema update enhances the existing design by adding critical columns for improved curriculum management and student performance tracking within the university system.

# Key Updates:

## 1. Students Table:

General GPA and Specialty GPA columns have been added to track students' overall academic performance and their GPA within their chosen major or specialty.

## 2. Curriculum Table:

A new Total Credits column has been added to indicate the total number of credits required to complete a curriculum.

## 3. Student Curriculum Table:

A Completed Credits column has been added to track the number of credits each student has completed toward their curriculum.

![updated scheme](https://github.com/user-attachments/assets/7dc9de0e-f22a-475b-b28f-5db7e564a10f)

**Comment by nelson-escalona** [comment]
LGTM👍
