### ISSUE TITLE
Create CRUD functions for GPAs and credits.

### ISSUE THREAD

**Issue by nelson-escalona** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#153]
Objective:
Create CRUD functions to get the students GPAs (General and Specialty), the remaining credits and the total credits in the curriculum attached to the student.

Description:
For this issue, we want to create CRUD functions to get the students GPAs (General and Specialty), the remaining credits and the total credits in the curriculum attached to the student.

Expected Outcome:
Fully functional CRUD functions that get a given students GPAs, credits and the total credits of the students curriculum.

Difficulty:
4

Priority:
4

Assignee:
@Jeanpaul-Ortiz

**Comment by Jeanpaul-Ortiz** [comment]
calculate_total_credits: Calculates the total credits for a specified curriculum by summing the credits of all courses associated with a given curriculum_id. Joins curriculum_courses and courses tables based on course_code to perform the calculation.

fetch_remaining_credits: Computes the remaining credits for a student by subtracting completed_credits from the curriculum’s total credits. Uses student_curriculum and curriculum tables to retrieve the relevant data.

fetch_general_gpa: Retrieves the general GPA of a student from the students table based on student_id. Returns the GPA value or None if no record is found.

fetch_specialty_gpa: Retrieves the specialty GPA for a student, similar to the general GPA function. Accesses the students table and returns the specialty GPA or None if not available.

**Comment by Jeanpaul-Ortiz** [comment]
![image](https://github.com/user-attachments/assets/fce19974-ea91-4523-8ace-d39b29e537f0)
![image](https://github.com/user-attachments/assets/b705dfa4-08de-4947-b625-16a0a85af9be)
![image](https://github.com/user-attachments/assets/d06b6d81-978c-458e-8ffe-3077274af5bc)
![image](https://github.com/user-attachments/assets/15bb5d03-2ff8-40c1-a999-433f531f926e)

**Comment by nelson-escalona** [comment]
LGTM👍🏼
