### ISSUE TITLE
Create a parsing tool for the document with the UI content strings

### ISSUE THREAD

**Issue by cristianMarcial** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#156]
## Description
A module with an algorithm that receives as input the csv document defined in issue #154, which contains the UI context strings in different languages will be created. This algorithm will parse the document and organize the UI content strings in a dictionary structure, in which its keys representing the modules are the first column of the document (except for the one that contains the identifier string "LANG"), and its values ​​will be an indexed list containing the UI content strings of the row corresponding to each module.

## Objective
In a module, create the functions or functionalities necessary to separate the content of the document with the UI context strings (UCS) into two dictionaries: one with the UCS in English, and another with the UCS in Spanish. These two dictionaries will have as keys the modules that are in the first column, and the rest of the elements in the rows of the modules will be put in a list that will be the value corresponding to their respective key.

The parser will be given the ability to discern the language to which the rows belong, by a conditional statement that causes that when the element of the first row is the string "LANG", the element that follows it, which is the name of the language in which the UI content strings below the read element are (as shown in the code snippet indented in the comment of issue #154) will be a key of the dictionary, while the rows below the "LANG" row will be its values.

To clarify how the dictionary to be populated should look, use this example:

```py
UI_content_strings =
{
"english": {"mod_1" : ["example of text", "some words"],
           "mod_2": ["example of text", "some words"],
           },

"spanish": {"mod_1" : ["ejemplo de texto", "palabras"],
           "mod_2": ["ejemplo de texto", "palabras"],
           },
}
```

The "english" and "spanish" keys, being members of the UI_content_strings dictionary, facilitate the change of language, since you only have to change the parameter within UI_content_strings[parameter] to have the UI content strings being displayed in the desired language.

## Requirements
- The created algorithm is capable of receiving as input the document with the UI content strings located in its respective directory
- The algorithm can return a dictionary as described in the code fragment in the Objectives section
- The returned dictionary can be imported by other modules of the application

## Time Constrains & Deadline
In order to continue working with the rest of the MLS functionalities we must have this done as soon as possible. Therefore, the deadline must be days before the second sprint.

## Difficulty
5, since parsing skills and knowledge of handling libraries that handle files and strings are required.

## Priority
5, it's necessary to have this set as soon as possible in order to continue working with the rest of the MLS functionalities.

## Suggested Assignees
@Yamil-Serrano, @cristianramos9

**Comment by Yamil-Serrano** [comment]
@cristianMarcial  I successfully implemented the CSV parser to load multilingual content into a nested dictionary structure. The parser reads each line of the CSV file and organizes it by language and module. Below is a preview of the code and output. Here is a screenshot of the code and the result:

![image](https://github.com/user-attachments/assets/3f867af3-f1ac-481a-9dfa-96d99d967992)

I’d like guidance on how to test this parser within the RegiUPR app. Specifically.

**Comment by cristianMarcial** [comment]
@Yamil-Serrano Great. You can put it on line 9 of the ~/src/language.py module. I'll make some changes and then approve it for eventual closing by the managers.

**Comment by cristianMarcial** [comment]
just modified the module adding on it the correct path of the doc. This task has been completed.
