### ISSUE TITLE
[Lecture Topic Task] Develop a Petri Net diagram

### ISSUE THREAD

**Issue by Gian-Go** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#158]
Objective:
Develop a Petri Net diagram that will showcase competing processes with common resources.

Description:
By designing the diagram, it will provide clarity to the bigger picture regarding the project system and its logical interactions within. A Petri Net utilizes conditions (Condition Event Networks) / places (Place Transition Networks), events, and links in its presentation. Each is represented by circles, boxes, and arrows, respectively. A link is used to connect a condition to an event and vice versa, but a condition cannot be linked to another condition. The same is true for events, which cannot be linked to other events directly. In the case of CENs, markings are used within conditions to represent fulfillment of a process. For PTNs, markers work to denote space being taken within a place and links have weight.

Requirements:
-  Understand Petri Net diagrams and how to design them correctly.
-  Ensure the diagram showcases relevant processes and resources utilized within the projects to justify the use of said diagram.
-  Review the project processes for any one such process that may not already be represented by another diagram in the existing documentation.

Time Constraints:
November 19th

Completion Criteria:
The new diagram successfully represents the desired elements.

Difficulty:
4

Priority:
4

Suggested assignees:
2

**Comment by Gian-Go** [comment]
> If there is still a vacant position, I am willing to work on this. In the last milestone (#120) , i also got to work with diagrams related to the operation of the app (although they were not petri diagrams and had a different focus, but doing so helped me to better understand how to represent the operation of the project).

There is currently no one assigned to the task, but since you are interested, we can both work on it during the week.

**Comment by cristianMarcial** [comment]
i'm using https://petrinetsimulator.com/ for this. idk if there's a better free software for editing pn diagrams

**Comment by Gian-Go** [comment]
I've found the following site that seems to have more variety for diagram creation: http://biregal.com/. It maintains simplicity and should work for our purposes. 

However, should we require very specific functionalities and complex designs, the following site has a more developed layout, similar to Microsoft Word, though it will take longer to get familiar with and work on: https://app.smartdraw.com/editor.aspx?templateId=42663ff8-7ea9-47bf-bbb0-e774d298414d&noro=1&nsu=1.

I suggest we use the first option I provided to start and move to the other site should we require more versatility in designing options.

**Comment by cristianMarcial** [comment]
![image](https://github.com/user-attachments/assets/75932cf1-0d85-4efd-ab49-11a86269e4b0)

thoughts?

**Comment by Gian-Go** [comment]
> thoughts?
I feel the first linear section regarding the signup process might be redundant for a Petri Net Diagram, since there is no more than one moving part at a time during it. However, the following section regarding user login and credential validation between input and database is a nice, simple showcase of said process.

Meanwhile, I developed a different diagram (a Condition Event Network) that showcases the process of enrolling for a course. While the diagram does not show EVERY process and check we know occurs within the system, I opted to specify only the critical conditions such that it is boiled down into a more digestible representation of the course enrollment process.

![Screenshot 2024-11-19 210937](https://github.com/user-attachments/assets/154f92d4-d31d-439f-ac16-44919e407a61)

Open to critiques and suggestions for a better diagram, as mine is not final until it is scrutinized.

**Comment by Gian-Go** [comment]
![image](https://github.com/user-attachments/assets/00c03d62-ab74-44a2-96d0-cc5258fd96eb)

We have decided on a much simpler diagram that effectively showcases the relationship between students and available seats during the course enrollment period, where usually there are more students desiring a particular course section than there are available seats. there are two instances to show initial state and the conflict state when there are no available seats. they can be found in section 2.3.1 of the documentation.
