### ISSUE TITLE
Documentation Update for Sections 1.2.2 and 1.5

### ISSUE THREAD

**Issue by JorgeGuzman1** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#163]
**Objective:** Refine the documentation by modifying sections 1.2.2 (Needs) and 1.5 (Derived Goals) to improve clarity and focus.

**Description:**

**Section 1.2.2 (Needs):**

  The first part talks about the current situation and the latter about what we intend to do to improve the situation. These things should be covered elsewhere. Here we should focus only on the specific need of the students without mentioning the new system itself. 

**Section 1.4 (Derived Goals):**

  The current secondary goal (a notification system) aligns with the primary goal. A secondary goal could, for example, be to generate the domain description in such a way that it can also be used (or at least be the basis) for instructions on how to enroll (given to new students) or even for a documentation of the enrollment process that is used by administrators.

**Requirements:**

- Review the current content in Sections 1.2.2 and 1.5.
- Remove redundant or misplaced information.
- Ensure the revised sections maintain a clear, student-centered focus on needs and goals.
- The new text should be concise, informative, and aligned with the rest of the documentation.

**Deadline:** November 12, 2024 @ 4AM

**Completion Criteria:**

Section 1.2.2 focuses on student needs without reference to the new system.
Section 1.5 contains a revised secondary goal centered on creating a reusable domain description.

Difficulty:
3

Priority:
5

Suggested asignee: @saul108

**Comment by saul108** [comment]
updated version of Needs and derived goals that needed to be revised 
 1.2.2 Needs

While there is already a platform for student’s class enrollments, there is a need for a more efficient method to enroll in classes. Students require a system that assists their needs by providing course information and enrollment in one place. There is a need for students to have a platform which holds a record of their curriculum and the courses already taken, and courses that they need to take. Considering that courses have a tendency of actively changing information, there is a need to keep notifying the students which courses can be available, full, or restricted. Additionally, some courses have requirements which are needed to be enrolled in, there is a demand for a more efficient way of showing the courses that a student can select.


1.4 Derived goals 

By providing a more structured platform for students to enroll in courses, a secondary goal is to provide students with a more intuitive design which helps students with an introductory approach on how course enrollment works and what important information to look for. This can help freshmans on how to schedule classes for the semester. Another secondary goal of our platform is to help administrators to provide ease of access on course administration, as well as to implement a notification system that empowers students to access real-time updates on course availability, enrollment status changes, and waitlist notifications.


https://docs.google.com/document/d/1fm2_-xS2va0g5I8J_-kPfuVFM41GPkGdRXB2idwTLxs/edit?tab=t.0
