### ISSUE TITLE
[Lecture Topic Task] Identify and document Phenomena in the College Planning feature.

### ISSUE THREAD

**Issue by nelson-escalona** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#169]
## Objective:
Create a comprehensive list of observable phenomena in the "College Planning" feature.  This list will describe how the feature handles course management, GPA calculation, and data persistence. The goal is to aid both developers and testers in understanding and validating feature behavior.

## Description:
The "College Planning" feature allows students to organize their semesters by:

- Dragging and dropping courses into semester slots
- Checking their GPA's
- Tracking completed credits. 

To enhance clarity and support development and testing, the feature requires a breakdown of observable phenomena to document key interactions. Each phenomenon should capture user actions and system responses within the semester planning interface.

Documenting these phenomena will guide implementation, ensure consistent behavior, and provide a basis for validation and testing.

## Expected Outcome:
A comprehensive list of phenomena that describe how the feature handles course management, GPA calculation, and data persistence.

### Times Constraints: 
Complete by **November 24, 2024**.

### Difficulty: 
**5**

### Priority: 
**4**

### Assignees: 
@nelson-escalona and @carlospepin23

**Comment by carlospepin23** [comment]
The task to document the phenomena for the "College Planning" feature has been successfully completed. Please find the attached file for review and reference.
[Phenomena Documentation for College Planning Feature.pdf](https://github.com/user-attachments/files/17896570/Phenomena.Documentation.for.College.Planning.Feature.pdf)
