### ISSUE TITLE
End to end integration of the semesters table.

### ISSUE THREAD

**Issue by nelson-escalona** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#173]
Objective:
Integrate the front end and the back end of the semesters table in the college planning feature so that the semesters are correctly updated in the database when a course is dragged into the semesters table. 

Description:
In the "College Planning" feature, a semesters table is available to the student so that he can drag and drop courses and plan out their semesters. All of this data is supposed to be pushed to the database, using previously defined functions that were worked on in M2. For this issue, the goal is to successfully implement these functions with the front end, ensuring that the front end is updating these courses in the database and to assign a semester object to each semester in the front end.

Expected Outcome:
Using the Juan del Pueblo dummy user, we want to be able to assign a semester object to each semester and successfully update the courses added to the semesters in the front end. If we drag and drop a course into a semester and the semester object updates with the course and the database is updated with that course, then the end to end integration has been successfully implemented.

Difficulty:
5

Priority:
7

Assignee:
@nelson-escalona , @J3SSY-ANDU , @Jeanpaul-Ortiz

**Comment by nelson-escalona** [comment]
### Semesters Full Integration Completed

Semesters end to end integration has been completed. Right now, a course can be dragged into a semester and it is automatically saved into the database. If the user logs out and logs back in, his planned courses are displayed in the corrects semesters. 

---

### Video

This is with the "Juan Del Pueblo" dummy user. This is all working on

[Screencast from 27-11-24 13:00:13.webm](https://github.com/user-attachments/assets/ab4948dc-84c7-4de4-9c9c-199a89c7371e)

**Comment by Ar2691** [comment]
Looks good!!
