### ISSUE TITLE
Merge Milestone 2 Branches for College Planning Feature

### ISSUE THREAD

**Issue by carlospepin23** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#175]
## Objective:
Merge all milestone 2 branches from the College Planning team into a single consolidated branch.

## Description:
This task involves combining the individual branches developed for milestone 2 of the College Planning feature into one branch. The purpose is to streamline the integration process and prepare for final testing and deployment. Each branch should be reviewed for conflicts, and any issues must be resolved before merging. 

## Requirements:

- Review and understand the changes in each milestone 2 branch.
- Resolve any merge conflicts that may arise during the process.
- Ensure all milestone 2 features are present and functioning as expected.
- Document any conflicts encountered and how they were resolved.

## Time Constraints:
Complete by Friday, November 15.

## Completion Criteria:
A single, stable branch containing all milestone 2 features is created.

### Assignees:
**x1** Developer

### Difficulty:
**3** (Straightforward task involving merge operations and conflict resolution.)

### Priority:
**6** (High priority to maintain progress on the College Planning feature)

**Comment by carlospepin23** [comment]
## Report on Branch Merging for Milestone 2
### Summary:
I have successfully merged the following branches into the merged-collegeplanning-m2 branch:

- `Courses-Elegible-To-Take`
- `College-Planning`
- `CRUDSemesterFuncs`
- `SemesterPlanning-Class`
- `college-planning-ui`
- `college-planning-ui-delete-table`

### Conflict Resolution:
During the merging process, there was a minor conflict with the .gitignore file, specifically related to the __pycache__ directory while merging college-planning-ui. The conflict has been resolved, and all changes have been integrated successfully.

### Current Status:
The merged-collegeplanning-m2 branch is now ready and serves as a stable base for moving forward with Milestone 3. This branch is particularly prepared for the end-to-end integration of the Semester Table and Courses Table features.

**Comment by nelson-escalona** [comment]
LGTM👍
