### ISSUE TITLE
[Lecture Topic Task] Domain Facets

### ISSUE THREAD

**Issue by PedroRodz** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#181]
Objective:

To develop a comprehensive set of domain facets that categorizes and organizes the information in the project documentation. 
Description:

Creating domain facets involves identifying and grouping key topics, terms, and themes related to the project  into meaningful categories that reflect the structure and content described in the document named "Evaluation Criteria and Guidelines - Milestone 3" provided by the professor. 

Expected Outcome:

The final deliverable will be a well-organized set of domain facets for the documentation.

Difficulty: 3

Priority: 5

**Comment by keisanabria** [comment]
Read the document named "Evaluation Criteria and Guidelines - Milestone 3" and focused on the section of Domain Facets. Completed the task according to the definition of each facet: "Intrinsics," "Business Procedures," and "Human Behavior". Basing the each facet on the features of the RegiUPR app.
![image](https://github.com/user-attachments/assets/41023e6b-d15b-4083-99db-ac4d4c070463)
