### ISSUE TITLE
Update the logbook for Milestone 3

### ISSUE THREAD

**Issue by Gian-Go** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#183]
Objective:
Complete one last update to the logbook by the end of Milestone 3.

Description:
Upon culminating the milestone, it is necessary to ensure all product backlogs are recorded within the documentation, coupled with a brief description of the work done. This allows for an overview of when in the development process any and all implementations were completed.

Requirements:
Revise all relevant, completed tasks completed within the milestone and record them in the logbook.

Time Constraints:
November 27th

Completion Criteria:
All work done is recorded in the logbook.

Difficulty:
3

Priority:
4

Suggested assignees:
@Gian-Go 
@saul108

**Comment by saul108** [comment]
updated logbook with tasks from milestone 3 sprint 1 and 2. Still waiting for some tasks to close however all of them are documented for when they are ready to be added.

https://docs.google.com/document/d/1fm2_-xS2va0g5I8J_-kPfuVFM41GPkGdRXB2idwTLxs/edit?tab=t.0
