### ISSUE TITLE
[Lecture Topic Task] Create a TLA+ Specification for the Semester Planning Feature

### ISSUE THREAD

**Issue by carlospepin23** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#194]
## Objective:
Develop a TLA+ specification to formally model and validate the Semester Planning feature. Although the actual code implementation for this feature is complete, this TLA+ specification is being created to apply techniques covered in course lectures and as a recommended best practice for verifying the design. It ensures that all constraints and behaviors are correctly implemented while identifying potential areas for improvement.

## Description:
This task involves creating a TLA+ model for the Semester Planning feature, which allows users to manage semesters, track GPAs, and monitor completed credits. The model will define the core action `(CreateSemester, AddCourse, and CompleteCourse)` and validate key invariants using the TLA+ model checker (TLC).

## Completion Criteria:
A complete and validated TLA+ specification that:

- Models the Semester Planning feature’s core logic.
- Confirms all key constraints are met.
- Documents the results of the model checking and identifies any areas for improvement.

## Time Constraints:
Finish by **November 25, 2024**

### Difficulty:
**5**

### Priority:
**5**

### Assignee:
2x Developer

**Comment by carlospepin23** [comment]
## Summary of TLA+ Semester Planning Model and Outcomes

The task began with the development of a TLA+ model to define key actions such as `CreateSemester`, `AddCourse`, and `CompleteCourse`, alongside critical invariants like `GPAInvariant` and `CreditsInvariant`. In a collaborative pair programming effort, @nelson-escalona and I worked together to develop a well-commented codebase, explaining each step of the model for clarity and ease of understanding. 

![part 1](https://github.com/user-attachments/assets/952284a3-e2e0-4bd8-83aa-db6ab78c79af)
The Init block established the starting state, ensuring that no students had assigned semesters or courses at the outset. 

![part 2](https://github.com/user-attachments/assets/b339c513-ed4c-4eb6-b7d1-5b07c4840636)
![part 3](https://github.com/user-attachments/assets/5bebd8cd-d410-42ab-a589-05c1499afce4)
Logical constraints were embedded in each action, such as validating prerequisites and ensuring GPA calculations followed accurate weighted averages, providing a robust and reliable system design.
***

![part 4](https://github.com/user-attachments/assets/9ff31a4d-2229-44db-bc13-1c1aa3449324)
Once the specification was completed, the model was tested with constants representing a sample student, courses, and semesters. 

![part 5](https://github.com/user-attachments/assets/ae36dffd-2153-4440-928b-38d5e47d4687)
Using the TLA+ model checker (TLC), all possible states and transitions were simulated, guaranteeing a comprehensive analysis. The results validated that all constraints were met and confirmed the system’s logical integrity.

The TLA+ model, in addition to the testing benefits mentioned above, it laid a solid foundation for new features, such as course capacity limits or enrollment restrictions, can be added seamlessly and checked for consistency using the existing model.

The `.tla` file for this specification has been attached below.
[CollegePlanningTLAFile.zip](https://github.com/user-attachments/files/17895712/CollegePlanningTLAFile.zip)

**Comment by nelson-escalona** [comment]
LGTM👍🏼
