### ISSUE TITLE
[Lecture Topic Task] Unit Testing for Semester Planning Class and CRUD Functions

### ISSUE THREAD

**Issue by carlospepin23** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#195]
## Objective:
Develop and execute unit tests to ensure the reliability of the Semester Planning class and its associated CRUD functions. 

## Description:
This task involves developing automated unit tests for the `Semester Planning` class and its `CRUD operations` using Python libraries like `unittest` or `pytest`. The tests will simulate database interactions, verify data integrity, and handle edge cases to ensure robust functionality in semester creation, course assignments, data persistence, and error handling under various conditions.

## Completion Criteria:
- Comprehensive unit tests are created for the Semester Planning class and its CRUD functions.
- Tests validate functionality under both typical and edge-case scenarios.
- Mocked interactions simulate database operations effectively, ensuring independence from a live database.
- All tests are executed successfully.

## Time Constraints:
Complete by the **End of Milestone 3**

### Difficulty:
**4**

### Priority:
**3**

### Assignee:
1x Developer

**Comment by carlospepin23** [comment]
![part 1](https://github.com/user-attachments/assets/2758dc1b-4b12-4bef-b523-a9f98bf1a418)
![part 2](https://github.com/user-attachments/assets/84752be3-876d-499b-90e7-124252d7ca85)
I have developed unit tests for the `SemesterPlanning` class and its functions, all of which have passed successfully, as demonstrated in the attached pictures. The code is available in the respective branch for review.

**Comment by nelson-escalona** [comment]
LGTM👍🏼
