### ISSUE TITLE
Implementation of Course Selection Screen After Sign-Up

### ISSUE THREAD

**Issue by Carloscaban** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#196]
**Objective:** To ensure that students complete their academic profile by indicating which courses they have already taken or are currently taking, to facilitate accurate course planning and enrollment.

**Description:** Implement a new Course Selection Screen that appears immediately after successful registration. This screen contains two lists:

List 1: Courses from the student's curriculum, with courses the student should have already completed checked by default.
List 2: Only the checked courses from List 1, representing the courses the student is currently taking.

The purpose of having this screen is to accurately collect data about the student’s academic history and current enrollment. This allows the system to determine which courses the student is eligible to enroll in, ensuring the proper flow through the curriculum.

**Requirements:**

Create a new Course Selection Screen that appears right after successful sign-up.
List all courses in the curriculum in List 1, with the courses supposed to be completed by the current semester checked by default.
Populate List 2 with the courses from List 1 that are marked as taken, but allow students to select only those they are actively taking.
Implement a Confirm Selection button to finalize the selection process and save the student's course history to the database.
Add a Back button to return to the Sign-Up screen if needed.

**Time Constraints:** Should be done by the end of the week (Sunday, November 24th, 2024)

**Difficulty:** 6 - Requires the design and implementation of new UI components, complex logic for populating the lists, and additional database interactions.

**Priority:** 8 - Accurate tracking of student course history is essential for the effective functioning of the enrollment system and to provide the student with the correct course options based on their progress.

Assignees: @Carloscaban and @chriistiian99

**Comment by Carloscaban** [comment]
![Task screenshot](https://github.com/user-attachments/assets/e7fa9163-e6f0-441e-baed-7e88882fca52)

**Comment by Ar2691** [comment]
![Image](https://github.com/user-attachments/assets/957284f2-b44f-48a0-899f-c4de00d9bd68)
The **and Are Currently Taking** might misguide the user, because the other list is for the courses they are currently taking, right?

**Comment by Carloscaban** [comment]
No, in the left column the user has to select the previously taken and current classes, in the right column only current classes, this is the most effective method to do it without knowing anything of the student

**Comment by Carloscaban** [comment]
The right column is a filter of the left column
