### ISSUE TITLE
Research AWS Database Solutions for Python Integration

### ISSUE THREAD

**Issue by carlospepin23** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#20]
**Objective:**
- Conduct research on AWS solutions for implementing a database that can be accessed by Python scripts.

**Description:** 
- The goal is to identify and evaluate various AWS database solutions that can be integrated with Python scripts. This research will help us understand the available options, their features, and how they can be used effectively in our project.

**Requirements:**
- Explore different AWS database services.
- Evaluate how each service supports Python connectivity and integration.
- Compare performance and cost in the context of the free tier.

**Time Constraints:**
- Complete by Tuesday, Sept. 10.

**Completion Criteria:**
- A report on the AWS database solutions evaluated.
- Recommendations based on the research findings.

**Difficulty: 3**
- The task involves research and comparison.

**Priority: 8**
- The task needs to be done soon to keep the project on track.

**Comment by carlospepin23** [comment]
# Report on AWS Database Solutions for Python Integration

**Objective:** To evaluate and select the best option for hosting a MySQL database for the ongoing project and to establish an effective connection using Python scripts.

## AWS Service Selection: (Amazon RDS)

After researching and evaluating the various options provided by Amazon Web Services for hosting MySQL databases, it was determined that Amazon RDS (Relational Database Service) is the most suitable choice for our needs.

### Justification:

Our database is relational, which makes options like Amazon DynamoDB impractical, as it is designed for non-relational databases. Although Amazon EC2 instances could be used to set up a database on a virtual machine, Amazon RDS offers a more streamlined solution by managing the database directly and handling additional configurations automatically. This approach also conserves computational resources, as an EC2 instance would provide access to other tools and features not necessary for our specific requirements.

### The benefits of using Amazon RDS include:

**Automatic Management:** Amazon RDS provides a scalable and managed solution for MySQL databases, adjusting capacity and storage as needed. This flexibility is crucial for adapting to the changing demands of the project.

**Security:** Amazon RDS includes advanced security features, such as backup and recovery options that ensure data integrity and availability. While the data handled for this project does not pose significant risks, these features would be essential for maintaining security and reliability if the project were implemented on a larger scale.

**Cost-Free Option:** Amazon RDS offers a free tier that includes 750 hours of Single-AZ instance usage, 20 GB of SSD storage, and 20 GB of backup storage per month for one year. This offer allows us to perform testing and development without incurring additional costs, making it ideal for the scope of our project.

## Database Connection:

To connect our Python application with the MySQL database hosted on Amazon RDS, I found that using mysql-connector-python would be advantageous. This official Oracle library enables interaction with MySQL databases from Python. Its benefits include:

**Official Library:** As an official Oracle library, it ensures compatibility and ongoing support for current and future MySQL versions.

**Connectivity:** It facilitates essential operations, such as creating connections, executing queries, and handling results effectively.

**Error Handling:** It provides robust mechanisms for managing errors and exceptions, ensuring that operations are conducted safely and reliably.

## Conclusion:

The combination of Amazon RDS for MySQL and mysql-connector-python offers a robust and cost-effective solution for managing and implementing our database in the project.

### Sources:

[Amazon RDS MySQL](https://aws.amazon.com/rds/mysql/pricing/?pg=pr&loc=2)
[MySQL Connector/Python Documentation](https://dev.mysql.com/doc/connector-python/en/)

**Comment by nelson-escalona** [comment]
LGTM.

**Comment by nelson-escalona** [comment]
Completion date was changed to Tuesday, Sept 10 since the service selection changed and research summary has to be updated.

**Comment by nelson-escalona** [comment]
LGTM
