### ISSUE TITLE
[Lecture Topic Task] Software Design Description

### ISSUE THREAD

**Issue by Gian-Go** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#200]
Objective:
Add a description of the project's software design in the descriptive part of the documentation

Description:
A new section must be added to the descriptive part of the documentation, establishing the decisions made regarding the software design behind the project. Essentially, we must explain why we designed the project the way we did. For example, why did we decide to use a certain programming language over another viable language? why did we decide to use PyQt5 for UI and backend purposes? Naturally some of these project decisions are inherently linked to the requirements, which will also need to be related to these decisions.

Requirements:
Review critical decisions made throughout the project relating to implementation methodology.
Review Domain, Interface, and Machine Requirements.

Time Constraints:
November 26

Completion Criteria:
The description effectively covers the software design of the project.

Difficulty:
4

Priority:
5

**Comment by saul108** [comment]
Added Software design descpription and integrated by referencing the requirements, tools, and test used.


Software Design Description:

Interface:
	Interface requirements focus on creating a user-friendly GUI to simplify the enrollment process for students. As mentioned on the 2.2.4 for interface requirements it includes a secure user registration for personal information, course visualization for enrollment, and notification systems. To meet such requirements PyQT5, a library for interface development in python was selected and used for its robust set of tools to design intuitive and scalable desktop applications. With PyQt5 it was possible to develop validation rules for email verification, password strength verification, and error notifications providing security for the user registration system. QtableView and Qdrag class were used to implement the schedule interface by only searching the courses, dragging them and dropping them into the calendar for scheduling. Upon changes on the schedule, real-time conflict and updates are provided. To test and validate the interface, Pytest-QT was used to automate widget interaction and  validate drag-and-drop system handled edge cases where schedules overlap. A/B (split testing) testing was performed to refine the notification system placement and design. Lastly usability testing with sample personas were conducted to ensure the interface met their expectations.

Logic Interface:
	Key functionalities for the logic interface includes: managing notification and personalized student schedules, handling user authentication securely, and real-time validation for prerequisites and course conflicts. The logic interface was implemented with Python which levers the compatibility with PyQt5. The design implemented was the Model View Controller (MVC) to ensure modularity. Bcrypt and email-validator libraries were used for password hashing and input verification providing authentication features to the users. Automated prerequisites validation and conflict detection which utilize custom scheduling algorithms to identify and result crashes dynamically. Schedule and Py-notifier libraries were used for periodic tasks, desktop notifications, and reminders of enrollment based on user profile and university calendar data. Using Unittest, functional testing was performed to validate logic accuracy. Edge case scenarios, such as failed login attempts or prerequisites were tested extensively. Stress testing ensured that the logic could handle simultaneous interactions from multiple users.

Database:
	The database requirements emphasize on scalability, data integrity, and efficient query performance. The database holds the information for each of the entities in the domains mentioned in section 2.1 and presented in the database schema for the data faculty on the figure 1 in section 2.3.1. The database was integrated with PostgreSQL due to its support for complex queries, relationships, and scalability. With PostgreSQL it was possible to create the schema Design for the Student, courses, sections, enrollment, and notification and also the relationships for student and courses via enrollment with foreign key constraints.  For integration, SQLAchemy was used as an Object-Relational mapping (ORM) to interact with the database from Python. It also provides an index of frequently queried columns in the database and procedures for conflict detection and prerequisites checks. Database integrity tests were conducted using pytest-postgresql to ensure accurate relationships and constraints. Stress testing with pgbench validated performance under high concurrent loads and query optimization techniques like indexing and partitioning were applied to reduce response time during peak usage.
