### ISSUE TITLE
[Lecture Topic Task] Statechart Diagram for College Planning Feature

### ISSUE THREAD

**Issue by J3SSY-ANDU** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#203]
Objective:
To create a statechart diagram illustrating the various states and transitions of the College Planning feature as users interact with the planner.

Description:
Develop a statechart diagram to represent the dynamic behavior of the College Planning feature. The diagram should capture the system's states (e.g., Idle, Viewing, Editing, Validation, Updating) and the transitions triggered by user actions, such as adding or removing courses, viewing semesters, and updating GPA or credit trackers.

Requirements:

Identify and include the key states for the College Planning feature, such as:
  Idle State: Waiting for user interaction.
  Viewing State: When the user is navigating between semesters or tabs.
  Editing State: When the user is actively adding/removing courses.
  Validation State: When the system is checking constraints like prerequisites or credit limits.
  Updating State: When GPA Tracker and Credit Tracker are being recalculated.
  Saved State: When changes are saved to the planner.
  Define transitions between states based on specific user actions (e.g., switching tabs, dragging a course, validating prerequisites).
  Use UML conventions to represent states and transitions clearly.
  Include at least one core scenario, such as adding a course to a semester.
Time Constraints:
Should be completed by the end of Milestone 3.

Assignee:
@J3SSY-ANDU 

Difficulty:
4

Priority:
4

**Comment by Jeanpaul-Ortiz** [comment]
![image](https://github.com/user-attachments/assets/a1c11c53-7fff-4eb2-b201-9b5ddb95dfe6)

This state chart illustrates the dynamic behavior of the College Planning feature, highlighting key states and transitions. The system starts in the Idle state, awaiting user interaction. Users can transition to Viewing to navigate semesters or tabs and then to Editing to add or remove courses. Upon completing edits, the system enters Validation to check constraints like prerequisites. If successful, it proceeds to Updating to recalculate GPA and credits, before reaching Saved, where changes are finalized. Transitions allow users to cancel or complete actions, ensuring a smooth flow between states. This state chart was collaboratively designed by @Jeanpaul-Ortiz and @J3SSY-ANDU.
