### ISSUE TITLE
Implement AWS Database Solution Based on Research

### ISSUE THREAD

**Issue by carlospepin23** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#21]
**Objective:**
- Implement the chosen AWS database solution that can be accessed by Python scripts, based on the research findings.

**Description:**
- Following the research on AWS database solutions, this task involves setting up and configuring the selected database service. The implementation should ensure that the database integrates effectively with Python scripts and meets the project’s requirements.

**Requirements:**
- Set up the chosen AWS database service (e.g., Amazon RDS, Amazon EC2).
- Configure database settings and access permissions.
- Implement Python scripts to connect to and interact with the database.

**Time Constraints:**

- This task will begin after the research phase is completed.
- Complete by Wednesday, Sept 11.

**Completion Criteria:**
- Database service is successfully set up and configured.
- Python scripts can connect to the database.
- Documentation of the setup process and any configuration details.

**Difficulty:** 7
- The task involves technical implementation and integration, requiring careful setup and troubleshooting.

**Priority:** 7
- The task is important for CRUD functions to be created and for project progression.

**Recommended Assignees:**
- 2x Developers

**Comment by nelson-escalona** [comment]
Completion Date is now **Wednesday, Sept 11** since research task has not been approved and we've been having some bugs during the testing process.

**Comment by nelson-escalona** [comment]
### MySQL Database Access on AWS EC2 Instance

We have successfully set up a MySQL database hosted on an AWS EC2 instance (`t2.micro`) as part of the Free Tier. The database is accessible globally via the instance’s elastic IP address, and it has been fully tested for functionality.

#### Key Details:
- **Instance Type**: AWS EC2 `t2.micro` (Free Tier)
- **Database**: MySQL with the approved schema already uploaded
- **Developer Access**: A user specifically for developers has been created
- **Elastic IP**: The EC2 instance is assigned an elastic IP for reliable access
- **Security Groups**: Port `3306` (MySQL) is open to allow external access

#### Handling Database Credentials:
To maintain the security of the database, credentials **must not be pushed to GitHub** or any version control platform.

- The database credentials are **documented** separately and securely.
- Only the **Team Lead (me, Nelson S. Escalona)** holds the document with the credentials.
- If you require access, **contact a manager**. The manager will reach out to the Team Lead to provide the credentials to you.

#### Additional Notes:
- Ensure your local environment is set up to connect to the MySQL database using the credentials you are provided.
- Only the **Team Lead (me, Nelson S. Escalona) has and will have access to the root AWS account. If somebody needs to change or add something to the database, they need to contact me or @carlospepin23 .

**Comment by Ar2691** [comment]
Create a test task to test the functionality of the database.

**Comment by nelson-escalona** [comment]
@Ar2691 Forgot to add it in the resolution. @carlospepin23 and I have tested the connectivity to the database and queried values in and out of the database.

**Comment by nelson-escalona** [comment]
@Ar2691 Just added the database testing to the resolution of this task.

**Comment by Ar2691** [comment]
> @Ar2691 Just added the database testing to the resolution of this task.

Is it added in this issue?

**Comment by nelson-escalona** [comment]
> > @Ar2691 Just added the database testing to the resolution of this task.
> 
> Is it added in this issue?

@Ar2691 Yes. In the original comment, I added that we did some testing.
