### ISSUE TITLE
Research of Implementation of CRUD Functions using Python and MySQL

### ISSUE THREAD

**Issue by J3SSY-ANDU** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#23]
Objective:
Conduct thorough research on how to implement CRUD (Create, Read, Update, Delete) operations using Python with MySQL databases. The goal is to identify the best Python libraries, potential challenges, and the most efficient methods to interact with MySQL databases from Python scripts using SQL queries, with a focus on learning SQL.

Description:
This task focuses on researching how Python can be used to interact with MySQL databases for performing CRUD operations. The research will involve identifying suitable Python libraries for connecting to and executing queries on MySQL databases. Additionally, it will include learning and understanding SQL, with a particular focus on writing efficient queries for CRUD operations. The findings will provide a foundation for designing a robust interface between Python and MySQL in future development.

Requirements:
-     Research and identify Python libraries that are commonly used to interact with MySQL databases.
-     Investigate the pros and cons of each identified library (e.g., mysql-connector-python, PyMySQL, etc.).
-     Explore compatibility and performance considerations when using these libraries with MySQL.
-     Learn and understand SQL, particularly how to write efficient SQL queries for performing CRUD operations (Create, Read, Update, Delete).
-     Study how CRUD operations can be implemented in Python using SQL with the recommended libraries.
-     Identify best practices for handling database connections, transactions, and security when working with MySQL from Python.
-     Document any performance considerations or optimizations when using MySQL with Python.

Time Constraints:
    The research will begin immediately and should be completed by Monday, Sept. 9.

Completion Criteria:
    Detailed research document summarizing the findings on suitable Python libraries for interacting with MySQL.
    Understanding of SQL syntax and how to perform CRUD operations through efficient SQL queries.
    Identification of the best library to use for CRUD operations with MySQL in Python.
    No implementation is required in this task; only research and documentation of findings are necessary.

Difficulty:
3 - This is a research task that involves reviewing Python libraries and learning SQL concepts but does not require implementation.

Priority:
8 - The task is critical as it sets the groundwork for future development and ensures the right tools and methods are chosen for CRUD operations.

Recommended Assignees:
    2x Developers to conduct research and compile findings.

**Comment by J3SSY-ANDU** [comment]
### **We Will Use MySQL Connector/Python**

We will use the **MySQL Connector/Python** library as it is the official and well-maintained tool for interacting with MySQL databases directly from Python. It provides a robust set of features, including support for **pure Python implementation**, meaning it doesn’t require any additional MySQL client software. It is cross-platform and integrates seamlessly with MySQL server versions 5.5 and above, including MySQL 8.0.

This library supports essential functionality such as **connection pooling**, **transaction management**, and **parameterized queries**, which are critical for writing secure and efficient database interactions. It also provides **SSL/TLS support** for secure connections, and its API is designed to be simple yet powerful, allowing Python applications to execute SQL queries, fetch results, and manage database transactions with ease. Additionally, its error handling mechanisms and support for multiple cursor types make it versatile for a wide range of database operations, from simple queries to complex transactions.

### **Combining SQL with MySQL Connector/Python**

The MySQL Connector/Python library allows you to combine SQL queries directly within Python code. SQL statements such as `SELECT`, `INSERT`, `UPDATE`, and `DELETE` are passed as strings to the library's execution methods, enabling Python to interact with the database. The library handles the connection, query execution, and fetching results, while SQL handles the specific data manipulation tasks.

### **Implementing CRUD Functions**

Using MySQL Connector/Python, CRUD operations (Create, Read, Update, Delete) are implemented by writing SQL queries as Python strings and executing them with the library’s methods. Below is a more detailed explanation of how to use these methods:

1. **`INSERT` (Create Data)**:
   - You use the `INSERT INTO` statement to add new records to a table. The data is passed as a tuple of values to the query.
   - **Syntax**: The query is passed as a string using the `execute()` method, with `%s` placeholders for parameterized queries.
     ```python
     cursor.execute("INSERT INTO table_name (column1, column2) VALUES (%s, %s)", (value1, value2))
     ```
   - After calling `execute()`, you must call `commit()` to save the changes to the database.

2. **`SELECT` (Read Data)**:
   - To retrieve data from the database, you use the `SELECT` statement. You can fetch a single row or multiple rows using `fetchone()` or `fetchall()`.
   - **Syntax**: The `SELECT` query is passed as a string to the `execute()` method, and then you fetch the results.
     ```python
     cursor.execute("SELECT column1, column2 FROM table_name WHERE condition")
     result = cursor.fetchall()  # or fetchone()
     ```
   - This retrieves data from the database based on the query conditions (e.g., filtering with `WHERE`).

3. **`UPDATE` (Update Data)**:
   - To modify existing records, the `UPDATE` statement is used, along with the `SET` keyword to define which columns to update.
   - **Syntax**: Similar to `INSERT`, use `execute()` with parameterized queries.
     ```python
     cursor.execute("UPDATE table_name SET column1 = %s WHERE condition", (new_value,))
     ```
   - Again, `commit()` must be called to save the changes.

4. **`DELETE` (Remove Data)**:
   - You can remove records from a table using the `DELETE FROM` statement.
   - **Syntax**: The query is passed to `execute()`, and after calling the query, you use `commit()` to apply the changes.
     ```python
     cursor.execute("DELETE FROM table_name WHERE condition")
     ```

In all CRUD operations, **parameterized queries** (`%s` placeholders) are highly recommended to prevent **SQL injection attacks** by safely passing user inputs.

### **Backend Interaction with the Database Code**

The Python backend will interact with the database by calling the CRUD functions defined in the database logic. Instead of directly embedding SQL in the backend scripts, the CRUD operations are wrapped inside Python functions in the database script (e.g., `create_student()`, `get_student()`). These functions execute SQL queries through the MySQL Connector/Python library. The backend will simply call these database functions as it would with any other Python function, passing the necessary arguments (like student data) and receiving the result (such as a database record). This abstraction allows for clean separation of concerns: the backend focuses on business logic, while the database functions handle direct SQL interactions.

---

### **SQL Syntax Overview**

In SQL, key operations are performed using powerful keywords:

- **`CREATE`**: Used for creating databases and tables.
- **`INSERT`**: For adding new data into tables.
- **`SELECT`**: To retrieve data from tables.
- **`UPDATE`**: For modifying existing data in a table.
- **`DELETE`**: To remove data from tables.
- **`WHERE`**: Filters records to specify which rows to affect in queries.
- **`JOIN`**: Combines rows from two or more tables based on related columns.
- **`ORDER BY`**: Sorts the result set of a query.
- **`GROUP BY`**: Groups rows that have the same values into summary rows.
- **`LIMIT`**: Restricts the number of rows returned by a query.
- **`ALTER`**: Modifies the structure of an existing table.

These SQL keywords, combined with the methods in MySQL Connector/Python, form the foundation for efficient and secure database operations within Python applications.

**Comment by nelson-escalona** [comment]
LGTM.
