### ISSUE TITLE
Implementation of CRUD functions following Sections table in database schema

### ISSUE THREAD

**Issue by PedroRodz** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#24]
Implementation of CRUD functions following Sections table in database schema

Objective: Implement create,read,update and delete functions along with getters and any other necessary functions to be used in sections class of the database

Description: In order to create a functioning persistent storage application and manipulate it, we need to create necessary functions and create getters to allow other teams access to important data as needed
Requirements:
	
	-Create crud functions
	-Create getters
	-Test to ensure proper functionality

Time Constraints:

    -Should be done one or two days at most after completion of the Implement aws database task so other teams can begin testing their work
    -Complete by Sept. 13

Completion Criteria:

    -Implementation of crud functions and getters

Difficulty: 3

    -Crud function implementation should be straightforward once database is implemented

Priority: 8

    -High priority to allow others to test their tasks

Recommended Assignees:
 
	1 developers

**Comment by Ar2691** [comment]
Add the branch name in which it’s being developed.

**Comment by nelson-escalona** [comment]
Looked over the sections file and it looks good. Unit testing will go underway later on.
