### ISSUE TITLE
Create a mockup for the Main Menu screen

### ISSUE THREAD

**Issue by RayMuvz** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#28]
### **Objective**:

Create a mockup of the Main Screen using the Figma software.

### **Description**:

We shall create a mockup of the Main Menu, in which all the main menu elements will be visually represented. 

### **Requirements**:

- Programs: We will be using the Figma program to develop this mockup
- Screen Design: Ensure it follows the same style as the login and profile screen. It should include a visual dashboard, as mentioned before, with a schedule and the enrolled classes represented visually and dynamically. 

### **Time Constraints**:

- Should be finished by September 9th, 2024.

### **Difficulty**:
1

### **Priority**:
3

**Comment by RayMuvz** [comment]
![Screenshot 2024-09-04 173558](https://github.com/user-attachments/assets/aaabde91-84f5-41f1-8335-5f2ddf18c5e7)

**Comment by williamgflores** [comment]
![IMG_6898](https://github.com/user-attachments/assets/2b2d91da-07c9-4bd5-a56f-b7f28a652cba)
<img width="704" alt="Screenshot 2024-09-17 at 10 10 51 PM" src="https://github.com/user-attachments/assets/31769899-29c9-434d-8b68-a29836aa2136">
