### ISSUE TITLE
Implementation of CRUD functions for the Courses and Program Faculty tables in the Database

### ISSUE THREAD

**Issue by Jeanpaul-Ortiz** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#29]
**Objective:**
The objective is to implement the Courses and program_faculty tables from the determined schema, by defining CRUD functions for both tables.

**Description:**
The Courses table will store the following properties of each course available: course_code, course_name, description, credits and program. While the program_faculty will store a program and the faculty, to which that program belongs. Along with the implementation of the tables, CRUD functions will be created in python to handle the data from these tables.

**Requirements:**
1. Create the Courses table with the following properties:
- course_code(Primary ID, varchar)
- course_name(varchar)
- description(text)
- credits(int)
- program(foreign key to program_faculty, varchar)
- 
2. Then create the program_faculty table with the following properties:
- program(Primary ID, varchar)
- faculty(varchar)

3.Implement CRUD functions for the Courses table:
- Create: A function to add a new course.
- Read: A function to retrieve a course by course_code or list all courses.
- Update: A function to update a course’s details based on course_code.
- Delete: A function to delete a course by course_code.

4.Implement CRUD functions  for the Program_Faculty table:
- Create: A function to add a new program and its associated faculty.
- Read: A function to retrieve a program by name or list all programs and faculties.
- Update: A function to update the faculty of a program.
- Delete: A function to delete a program by name, with considerations for courses that reference this program. Implement cascading delete or restrict delete as needed.

**Time Constraints:**
This task will be started September 10th and will be completed by September 12

**Completion Criteria:**
- The Courses and program_faculty tables are successfully set up in the database with all fields and relationships correctly configured.
- Python scripts for CRUD operations are fully functional and tested.
- Documentation of the setup process, table relationships, and the CRUD operations is provided.

**Difficulty:**
3-This task has a moderate difficulty since it relies in connections between both tables

**Urgency:**
8-Specifically the relation to Courses is needed in the Sections and Student_courses tables.

**Comment by nelson-escalona** [comment]
Looked over the functions and they look good. Unit testing will go underway later.
