### ISSUE TITLE
Create Executables for Linux Operative Systems

### ISSUE THREAD

**Issue by Yamil-Serrano** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#34]
**Objective:**
Ensure that the tuition system application can be packaged and executed on Linux operating systems.

**Description:**
We are developing a student-friendly tuition system application using Python. Currently, we are exploring tools like PyInstaller, PyOxidizer, cx_Freeze, or Nuitka to package the application into an executable format for Linux systems.

**Requirements:**

- Use PyInstaller, PyOxidizer, cx_Freeze, or Nuitka to create an executable file for Linux.

- Document the packaging process for Linux.

- Update the installation guide to reflect changes for Linux users.

**Time Constraints:**
Complete by Monday, Sept. 16.

**Completion Criteria:**

- A working executable file for Linux.

- Clear instructions on how to package for Linux.

- Updated installation guide for Linux.

**Difficulty:**
3 (Involves researching tools and performing testing).

**Priority:**
8 (High priority due to Linux-platform accessibility).

**Comment by cristianramos9** [comment]
Screenshot of a game created in python and launched from an executable created by pyinstaller.
Operating system is Debian 12.

PyInstaller can create a single-file executable from a python program.

![Screenshot_2024-09-16_11-53-56](https://github.com/user-attachments/assets/225d9fd6-344b-4e72-b841-9837aa632b44)

Pending: instructions.

**Comment by cristianramos9** [comment]
@Yamil-Serrano 
PyInstaller Instructions
(On Debian, may be different for other Linux distriibutions)

1. Install python3-pip (install command and package to install may differ between distributions)
`sudo apt install python3-pip`

2. Install/upgrade some needed libraries
`pip install --upgrade pip setuptools wheel`

3. Install pyinstaller
`pip install --upgrade pyinstaller`

4. Execute pyinstaller
`pyinstaller --onefile main.py`

**Comment by Yamil-Serrano** [comment]
@cristianramos9 Okay, those are the steps to install pyinstaller on Debian-based Linux operating systems. Pyinstaller does not have to be downloaded by the users of the app but rather by the developer for packaging the program.

**Comment by cristianramos9** [comment]
> Okay, those are the steps to install pyinstaller on Debian-based Linux operating systems. Pyinstaller does not have to be downloaded by the users of the app but rather by the developer for packaging the program.

Yes. End user only have to download the program executable and launch it (after changing mode).
I tested in a virtual machine, and installing a Linux operating system would install Python 3 by default, this is most likely true to most popular distros.
