### ISSUE TITLE
Make official documentation for the Database team.

### ISSUE THREAD

**Issue by nelson-escalona** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#38]
Objective:
Make a preliminary document with all the information of all the tasks worked by the database team.

Description:
We will be adding information to a google doc generated by the database team. This google doc will have all the documentation from the tasks that the database team worked on. From the database scheme, to the CRUD functions.

Implementation plan:
From this Friday, Sept 13, we will start adding the documentation to the google doc. 

Testing plan:

Deadline:
Wednesday, Sept 18.

Difficulty: 3
Urgency: 5

Assignee:
@carlospepin23 
@J3SSY-ANDU 
@Jeanpaul-Ortiz 
@PedroRodz

**Comment by carlospepin23** [comment]
[DATABASE_TEAM_DOCUMENTATION.pdf](https://github.com/user-attachments/files/17082330/DATABASE_TEAM_DOCUMENTATION.pdf)
