### ISSUE TITLE
Implement Local Database Integration with CRUD Operations for Student and Course Classes

### ISSUE THREAD

**Issue by Yamil-Serrano** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#39]
**Objective:**
 Implement database integration for the Student and Course classes, adding full support for CRUD (Create, Read, Update, Delete) operations using a local database for testing purposes.

**Description:**
The objective is to connect the existing Student and Course classes to a locally provided database, which will be used for testing CRUD operations. The database, along with its CRUD functions, will be provided by the database team. In the future, the system will be migrated to use cloud-based database services.

**Requirements:**

 **Database Setup:**
-   Download the local database provided by the database team.

-   Ensure that the structure of the local database aligns with the data models for Student and Course.

**Method Implementation:**

- Create: Add methods to insert new student and course data into the local database.

- Read: Implement methods to retrieve student and course data from the local database.

- Update: Add functionality to update existing student and course records in the local database.

- Delete: Provide the ability to remove student and course records from the local database.

**Data Validation:**

- Ensure proper validation before any operation (e.g., checking for existing records before creation, validating data formats).

- Testing: Perform all CRUD operations locally to verify the correctness of the implementation.

**Time Constraints:** 
Complete by Thursday, Sept. 19.

**Completion Criteria:**

- Full database integration with the Student and Course classes, using the locally provided database.

- Functional CRUD methods for managing student and course data locally.

- Unit tests for each method to ensure reliability.

**Difficulty:** 5 (Involves database integration and CRUD operations with a local database).

**Priority:** 8 (Critical for enabling persistent student and course data management for local testing).

**Comment by nicolle-feliciano** [comment]
I wish to be added to this task
