### ISSUE TITLE
Lecture Topic Task: Unit Testing for Student and Student Courses CRUD Functions

### ISSUE THREAD

**Issue by J3SSY-ANDU** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#43]
**Objective:**  
Develop unit tests to ensure the accuracy and reliability of CRUD functions for the `students` and `student_courses` database tables.

**Description:**  
This task involves creating automated unit tests for CRUD operations specifically for the **`students`** and **`student_courses`** tables using Python libraries (e.g., unittest, pytest). The tests should mock database connections, ensure data integrity, and handle edge cases.

**Implementation Plan:**
1. Set up testing environment using `unittest` or `pytest`, and utilize mocking libraries such as `mock` or `pytest-mock` to simulate database connections.
2. Write unit tests for each CRUD operation for the following tables:
   - `students`
   - `student_courses`
3. Ensure tests cover:
   - Basic operations (Create, Read, Update, Delete).
   - Handling of foreign keys between `student_courses` and `students` (e.g., ensuring a student exists before adding them to `student_courses`).
4. Include coverage for edge cases (e.g., invalid input, constraint violations, and referential integrity).
5. Mock database interactions to avoid relying on the actual database during testing.

**Testing Plan:**  
Tests will be run locally using Python's `unittest` or `pytest` framework. The focus areas are:
- CRUD operations for the `students` and `student_courses` tables.
- Handling of foreign keys in `student_courses` that reference `students`.
- Negative testing, ensuring the system handles errors gracefully (e.g., foreign key violations, invalid student IDs, etc.).

**Deadline:**  
Complete by **Milestone 2** October 7, 2024 deadline.

**Difficulty:**  
3 - Moderate.

**Urgency:**  
5 - High.

**Comment by nelson-escalona** [comment]
LGTM👍
