### ISSUE TITLE
Update database scheme to include curriculums.

### ISSUE THREAD

**Issue by nelson-escalona** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#69]
Objective:
Update the database scheme to include the addition of curriculums.

Description:
This task involves going over the database design and finding the best relation for curriculum integration into the database.

The end goal should be to:

- Have classes attached to specific curriculums.
- Classes to have a field of "suggested semester", which should follow the semester its suggested on the official curriculum.
- Classes to have a field that marks if the class was "failed", "completed" or "in progress" by the student.

***IMPORTANT:*** Who ever does this task **cannot**  completely change the previous database design. The purpose of this task is to add into the design the curriculums, that's it.

Implementation Plan:
Once this task is completed, we will download the new design into a .sql file for database integration.

Deadline:
Complete by Wednesday, October 2nd.

Difficulty: 3

Urgency: 3

Assignees: @nelson-escalona or @carlospepin23  (for now)

**Comment by carlospepin23** [comment]
# Database Schema Update Report
This database schema upgrades the existing database design adding support for curriculum management and course prerequisites in the university system.

## Curriculum Table:
Each curriculum is linked to a specific program and contains a set of courses that students must take to graduate.

## Curriculum Course Table:
The Curriculum Course Table links curricula to their associated courses and specifies the recommended semester for each course.

## Course Prerequisite Table:
The course prerequisite table defines the prerequisite relationships between courses, allowing for multiple prerequisites per course. 

![update db](https://github.com/user-attachments/assets/a6762814-7788-426d-a59c-be2ed91a91e4)

**Comment by nelson-escalona** [comment]
Looks good to me!👍

**Comment by nelson-escalona** [comment]
Looks good to me! 👍
