### ISSUE TITLE
Create mock up/visual design of College Planning feature.

### ISSUE THREAD

**Issue by nelson-escalona** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#72]
Objective:
Create a visual design that will be used as a base that the front end developers will follow.  

Description:
This task involves creating a mock up of the college planning app in an app like Figma, so that the developers can follow that design when creating the features front end.

Implementation Plan:
Once this task is completed, developers from the college planning team will have a base design to follow.

Deadline:
Complete by Friday, October 4th.

Difficulty: 4

Urgency: 5

Assignees: **somebody from the college planning team**

**Comment by PedroRodz** [comment]
**Jessy’s draft** @J3SSY-ANDU 
• Shows a more detailed current semester view with a schedule that show days and
time of classes
![image0](https://github.com/user-attachments/assets/93fe02cf-cf18-4aad-80fc-128f8168826e)
**Pedro’s draft** @PedroRodz 
• Shows all semesters for planning your college career beforehand and some
trackers students may find useful
![image1](https://github.com/user-attachments/assets/215a03fa-d9f0-48c6-b9f5-02c960deb0d8)
**Final approved revision with team’s input**
• Allows changing between both views
• Color coded to be more user friendly
• More intuitive adding of classes
• Shows classes taken as well
• Classes can be repeated and added to the planner
![RegiUpr - Course Planning(4)](https://github.com/user-attachments/assets/401edc22-646e-482b-958a-a323c62c5ff9)
***Subject to change**

**Comment by PedroRodz** [comment]
@nelson-escalona

**Comment by nelson-escalona** [comment]
Looks good to me!!

**Comment by PedroRodz** [comment]
@Ar2691 @michellebou Waiting approval of managers

**Comment by michellebou** [comment]
looks good!
