### ISSUE TITLE
Lecture Topic Task: Verification and Testing of Sections Class and its CRUD functions

### ISSUE THREAD

**Issue by PedroRodz** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#76]
Objective

To ensure the correctness and reliability of the implementation by verifying model properties and conducting thorough unit testing of the sections class of our project.

Description

The task involves verifying that the implementation meets specified requirements through unit testing, validating that the implemented functions return expected results. For example, calling the update function with the parameters '080' and 'S114' on the entry ('080', 'INSO4101', 'Marko Schutz', 'MWF', '2:30p-3:20p', 'S113', 'Presential', 100) should change the entry to ('080', 'INSO4101', 'Marko Schutz', 'MWF', '2:30p-3:20p', 'S114', 'Presential', 100). Each function will have corresponding tests.

Implementation Plan

    Create Unit Tests using the unittest library in python.

Assignees - @PedroRodz 

Milestone-2

Deadline - Oct 8

Difficulty-3

Priority-3

@Ar2691 @michellebou

**Comment by Ar2691** [comment]
Specify what implementation would be tested with the unit tests

**Comment by PedroRodz** [comment]
> Specify what implementation would be tested with the unit tests

Ya se lo añadí al título.

**Comment by PedroRodz** [comment]
![Screenshot (9)](https://github.com/user-attachments/assets/8d659add-4391-44ea-869e-560166b16f77)
Done

**Comment by nelson-escalona** [comment]
Looks good to me!👍
