### ISSUE TITLE
Implement Admin Role for RBAC System with Full Permissions and Access Control

### ISSUE THREAD

**Issue by Yamil-Serrano** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#77]
**Objective:**
Implement the Admin role in the Role-Based Access Control (RBAC) system to manage full access and administrative functionalities.

**Description:**
This task focuses on creating the Admin role within the RBAC system, ensuring it has full access to all system features. The Admin role will be able to manage user accounts, course details, enrollment requests, and the academic schedule.

**Roles and Permissions:**
**Admin:**

- Full access to all system features.
- Can manage user accounts (create, edit, delete).
- Can modify course details.
- Can approve or reject enrollment requests.
- Can manage the academic schedule.

**Features:**

1. Role Definition:

- Define the Admin role in the system with the corresponding permissions.

2. Permission Enforcement:

- Restrict actions like user management and course modifications to Admins only.
- Ensure that the Admin role can access and perform all required administrative actions.

3. Testing and Validation:

- Test that the Admin role has full access to all system features.
- Verify that only Admins can perform restricted actions like managing users and modifying course details.

**Requirements:**

1. Role Definition:

- Implement the Admin role in the system with full access to system features.

2. Permission Management:

- Ensure the Admin role can perform administrative actions, including user management and course modifications.

3. Testing:

- Perform tests to confirm that the Admin role has unrestricted access.
- Validate that non-admin users cannot access admin-level functionalities.

**Time Constraints:**
Complete the Admin role implementation by Thursday, Oct. 10.

**Completion Criteria:**

- Fully implemented Admin role with full access to system features.
- Permissions enforced correctly for Admin functionalities (user and course management).
- Unit tests covering all key Admin actions and ensuring security.

**Difficulty:**
6 (Requires role definition and enforcing permissions for Admin).

**Priority:**
9 (Critical for system administration and managing core features).

**Comment by Ar2691** [comment]
Break the task into smaller parts

**Comment by JRRR0912** [comment]
We could break the task in three parts. We may use the features specified in the issue to break the task.

Task #1: Role Definition 

- Define the Admin role in the system with the corresponding permissions.

Task #2: Permission Enforcement

- Restrict actions like user management and course modifications to Admins only.
- Ensure that the Admin role can access and perform all required administrative actions. (Can be made into another task)

Task #3: Testing and Validation

- Test that the Admin role has full access to all system features.
- Verify that only Admins can perform restricted actions like managing users and modifying course details.


We should do the same for the other roles we may add and implement.

**Comment by Ar2691** [comment]
Role definition should be a brainstorming of what possible roles and privileges we could have in our application.

**Comment by Yamil-Serrano** [comment]
> Role definition should be a brainstorming of what possible roles and privileges we could have in our application.

Thanks, that is actually a good idea, to do a task related to that to get an idea of ​​the roles that we will implement in the application.

**Comment by Carloscaban** [comment]
@michellebou @Ar2691 Please assign me to this issue.
