### ISSUE TITLE
Integrate Semester and Course Planning into Database Schema

### ISSUE THREAD

**Issue by carlospepin23** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#78]
### Objective:

Update the database schema to include the semester planning tables.

### Description:

This task involves reviewing the database design, structuring the logic, and incorporating the necessary tables for developing the Course Planning feature.

### Requirements:

- Create tables for semester planning, allowing students to plan courses for custom semesters.
- Maintain existing database relationships while integrating the new course planning functionality.

### Time Constraints:

Complete by Tuesday, October 8.

### Completion Criteria:

- Semester planning functionality added, allowing for custom semester creation and course management.
- The database schema updated and saved as a .sql file for integration.

_IMPORTANT_: Whoever does this task must **not** completely change the previous database design. The purpose of this task is to integrate course and semester planning in the existing schema.

#### Difficulty: **3**

The task involves understanding existing database relationships and incorporating new tables while maintaining consistency.

#### Priority: **4**

This task is important for enabling semester planning in the application, which is crucial for the Course Planning feature and the overall student experience.

#### 1x Developer

**Comment by carlospepin23** [comment]
# Database Schema Update Report
This database schema upgrade includes detailed semester planning for students, facilitating the selection of courses in alignment with their academic programs.

## Student Curriculum Table:
The _student_curriculum_ table links students to their respective curriculums through the curriculum_id and student_id properties.

## Semester Planning Table:
The _semester_planning_ table is designed to track individual students' semester plans. Each entry represents a specific semester plan associated with a student. This table captures the semester name and links it to the student through the student_id property.

## Planned Courses Table:
The _planned_courses_ table is connected to the semester_planning table through the planning_id property. It records the specific courses that a student intends to take during a given semester.

![v2](https://github.com/user-attachments/assets/6db32153-f3f0-46ce-99cb-eb692c51f8bf)

**Comment by nelson-escalona** [comment]
Looks good to me!

**Comment by carlospepin23** [comment]
Waiting for managers' approval @Ar2691 @michellebou
