### ISSUE TITLE
RESEARCH on implementing a web scrapper

### ISSUE THREAD

**Issue by cristianMarcial** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#80]
Objective: 
Conduct thorough research on how to implement a web scrapper that can segregate and concatenate the information provided on a web page and place it neatly into a file to be imported into our application.

Description: 
First we will look at the page that our web scrapper must read (in this case, www.uprm.edu/registrar/sections/), identify where (and how) the information that we will tokenize in the code to be scraped is separated (in this case, the information of the courses of this semester, such as department, sections, etc.) and how we will segregate that information into a separate document that can be read by our application.

Requirements:
- Research and identify what resources are needed to create (and run) a web scrapper
- Research how to separate the source code obtained with the scrapper.
- Investigate how to tokenize the information that was scraped.

Time Constrains:
Not before October 7th, we must already have all the information required in the requirements.

Completion Criteria:
Have all the information listed in the requirements section.

Difficulty:
4, since it requires research and knowing soon how to discern a lot of information regarding web scrapping.

Priority:
8, it is extremely important to have this information in order to continue with the other tasks of the curriculum restructuring team.

**Comment by cristianramos9** [comment]
It is known how to get a web page and get a table from such document.
A python file that demonstrates this was pushed to branch 'M2_curriculum'.
However, research is still underway to know how to extract specific data from an html document.

**Comment by cristianMarcial** [comment]
[Research_Curriculum.pdf](https://github.com/user-attachments/files/17319399/Research_Curriculum.pdf)

Done
