### ISSUE TITLE
Implement the course catalog to the Database

### ISSUE THREAD

**Issue by cristianMarcial** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#82]
Objective:
export the information to the application Database once the information extracted with the parser to be developed has been tokenized.

Description:
A functional module will be created to iterate on the information collected, each course will be uploaded to the database using the developed CRUD functions.

Requirement:
- The course information is separated by parts (department, professors, sections, schedules, co-requisites).
- The database can contain this information separately.
- Upload the information and be able to record that the information is in the database.

Time Constrains:
Before October 10.

Completion Criteria:
Comply with everything listed in the requirements section.

Difficulty:
4; absolute knowledge of the operation of the modules with the CRUD functions and the structure of the Database is required.

Priority:
5

Suggested Asignees:
Chese157 y JorgeGuzman1

**Comment by michellebou** [comment]
@Ar2691

**Comment by cristianMarcial** [comment]
Although I managed to entry the three dummy courses to the database, for some reason create_section() doesn't recognizes any of them on the catalog. I lack knowledge about how the DB works but if this isn't a bug on the DB, i don't know what else i can do to export the sections
![Screenshot (1069)](https://github.com/user-attachments/assets/9e4fbcfa-7737-4fbf-b5ef-5c4897ac313c)
![Screenshot (1070)](https://github.com/user-attachments/assets/263d6de2-e35c-4ed4-830c-ad4990f49f62)
