### ISSUE TITLE
Make new Additions to Documentation for Milestone 2

### ISSUE THREAD

**Issue by Gian-Go** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#85]
Objective:
Make additions to the documentation pertaining to milestone 2 guidelines.

Description:
There is new content that must be added to the documentation, such as new features implemented within milestone 2, improvements to domain description, requirements, etc. Also, new lecture topic applications will be added. Since it is not yet the end of the milestone, these additions are not final, as more will naturally occur during the latter half of the milestone.

Requirements:
- Document new completions by developers and implemented features.
- Ensure additions comply with previously set guidelines.

Time Constraints:
October 10

Completion criteria:
The additions reflect progress within the project at the halfway point of the milestone.

Difficulty:
3

Priority:
4

Suggested number of Assignees:
2

**Comment by saul108** [comment]
https://docs.google.com/document/d/1WvPumtALrkqYM8bgXZRwuFdoEh5l9ka6etdCJM-uFX8/edit?usp=sharing

Added topic closed tasks information of:
- Defining user requirements for Course Planning
- Database schema updates
- Interface requirements
- Verification and validation of CRUD methods
