### ISSUE TITLE
Role Definition and Privilege Mapping for RBAC System

### ISSUE THREAD

**Issue by Yamil-Serrano** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#89]
**Objective**
Define and document all possible roles and their corresponding privileges within the Role-Based Access Control (RBAC) system to ensure clear organization and management of access control within the tuition application.

**Description**
This task involves brainstorming and outlining all necessary roles and their associated privileges for the tuition application. The goal is to create a structured hierarchy of roles with detailed privileges, facilitating clear understanding and implementation for developers. Additionally, a visual diagram will be created to map the relationships between roles and their privileges, serving as a reference for future development tasks.

_**Initial Roles and Privileges:**_

1. **Student**

**_Privileges:_**
- View and edit own profile
- Add courses during tuition process
- Remove courses during tuition process
- View academic progress
- Enroll in courses during tuition process
- Unenroll from courses during the semester
- View personal schedule

2. **Admin**

**_Privileges:_**
- Access student information (view, edit)
- Approve tuition requests
- Reject tuition requests
- Add courses to student schedules
- Remove courses from student schedules
- Manage course catalog
- View and manage academic schedules
- Generate reports (e.g., enrollment statistics, academic performance)

3. **IT Support**

**_Privileges:_**
- Full system access ("god" mode)
- User account management (create, edit, delete all user types)
- Reset passwords for all users or for one in specific
- View and modify all system settings
- Access and modify database directly
- Manage system backups and security
- Monitor system performance and logs
- Troubleshoot technical issues across all modules

**Features:**
- Role Brainstorming

**Action Items:**
- Identify and list all potential roles required for the application beyond the initial roles provided (Student, Admin, IT Support).
- Define the responsibilities and privileges for each new role.
- Ensure that each role aligns with the application's functional and security requirements.
- Privilege Mapping.
- Create a comprehensive diagram (e.g., flowchart, UML diagram) that visually represents the relationship between roles and their privileges.
- Use tools like Lucidchart, Draw.io, or similar to design the diagram.
- Ensure the diagram is clear, organized, and easily understandable for all team members.

**Time Constraints:**
Complete the role definition, privilege mapping, and visual diagram creation by Thursday, October 10th.

**Completion Criteria:**
- Comprehensive Role List: All necessary roles are identified and documented with their respective privileges.
- Privilege Mapping Diagram: A clear visual diagram illustrating the connections between roles and privileges is created and included in the project documentation.
- Review Feedback Incorporated: Feedback from the team review has been addressed, ensuring the roles and privileges are accurate and complete.

**Difficulty:**
5 – Requires thorough brainstorming, organization of roles and privileges, and creation of a comprehensive visual mapping.

**Priority:**
8 – Essential for establishing a solid foundation for access control, facilitating secure and efficient system administration and feature management.

**Comment by Yamil-Serrano** [comment]
@Ar2691 @michellebou @RayMuvz the diagram, which can be accessed through the following [link](https://mermaid.live/edit#pako:eNp9lE1v2kAQhv_KaqX0RBIb2xg4VEJNW-UQNSokh5qo2qwHs429a-1HUhrlv3f8hWkw5WDA8-w7O-_M7ivlKgU6p5lm5ZasrtaS4Oe7yiGpHuaBnJ9_JEvrUpA2ab8feqoOL9JCyKR-vg9dr34uXVkqbZPrFWl_ItRgZ2edNLnV4lnkkIFpQt37Ov2tn9xqtcE4-UA-S63yvOj3geEau0fsXsDLJaTCkrJZcMSMcaMp4cppg-W9jwbJdyjUM5wEwjoFYZylUAhepck0mGMwSpqNEiFPik2SOwkNtdGqOMnFTdIStFGS5cTwLaSuLm5vZG3_kY3N27pJ6M4NkyyDvbfXcqPaXIs216Lyh3MsiJiWEkNUkCxKLP0ZLjX8Am6JdcIK1fX_MG3Ypf30T3UYaIGo6gjqDPjeQ5NOpQEIZ5blKhvIF-_LbF3qxeIWmXbIvo3mJDtLvoIEzSwQDdX0mkPX-6E-sr4f_fYkYAOWO2OhwCG-M6BJs4mDSa6YDh4nXxzOhWlWsKYn5yRTKSnwzA6sCJJaFVHlsG_F_9RDnHMDeEqYMS9Kp2aAiZrThNnEZtdtBBdZIbOef1_kJFkB30rBcU6_lZVxOBYH8pMOxD41yim28pEZGGCmnWOPjD-50qBzBrjTwu4G6BkqSmGVrk7KRml0gMMlTslQet9LVlq5R-z5Vikc4P2uhTGuHgQ6ogWgikjxhnytJNbUbtHSNZ3jz5TppzVdyzfkmLNquZOczq12MKKonG3pfMNyg_9ciTXClWB4zRYdUjL5Q6liD-F_On-lv-nc94KLYOxNw8ifeNPxOJiN6I7Og8i_8P1w4vtREHpjL34b0T-1gncRx8HMD0M_moUxrhjR6g5U-qa53etL_u0vS1vdFQ), has been completed. This diagram effectively illustrates the key components and relationships involved in the system design.

Please note that the current version of the diagram is flexible and can be adjusted to accommodate any additional or removed privileges as deemed necessary. If you identify any areas that need modification, feel free to suggest changes, and I will ensure that the diagram accurately reflects the required functionalities and structure.

Here is a PNG example of the diagram for reference:
![mermaid-diagram-2024-10-07-203446](https://github.com/user-attachments/assets/3aab39de-a9cf-4930-8866-66ff6a9bf827)

**Comment by Ar2691** [comment]
I recommend you change the role name from IT support to something else. An example would be super admin. Apart from that, good work.
