### ISSUE TITLE
Create Course Class for Student Eligibility

### ISSUE THREAD

**Issue by Jeanpaul-Ortiz** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#92]
Objective:
Develop a Python class that represents course information, including whether a student can take or is currently taking a course. This class will allow the system to return objects that the front-end team can use to display relevant course data.

Description:
This task involves creating a class that contains the following attributes:

class_name: The name of the course (e.g., "Calculus I").
class_code: A unique code for the course (e.g., "MATE3171").
credits: The number of credits for the course.
suggested_semester: The recommended semester for the student to take the course.
can_take_course: A boolean that determines if the student is eligible to take the course.
is_taking_course: A boolean that indicates if the student is currently enrolled in the course.

Implementation Plan:
Define the Course class with the required attributes.
Validate the class attributes (e.g., ensure credits are integers, boolean fields are correctly set).
Ensure the class can be used easily by other components, especially for interaction with the database.

Testing Plan:
Create unit tests to instantiate the class with valid and invalid data.
Ensure that objects of the class can be serialized into a format the front-end can use
Write test cases for scenarios where can_take_course and is_taking_course have different boolean values.
Deadline:
Complete by October 9, 2024.

Difficulty:
3-This task involves basic object-oriented programming with no complex logic.

Urgency:
4-This is foundational work required before other features, like CRUD operations for course eligibility, can be built.

**Comment by Jeanpaul-Ortiz** [comment]
A class named CourseEligibility was created to represent course information with attributes for the class name, class code, credits, suggested semester, whether a student is eligible to take the course (can_take), and whether the student is currently enrolled (is_taking). The class includes methods to update the can_take and is_taking statuses and implements a __repr__ method to provide a clear string representation of the object for easier debugging and interaction with the front-end team. This structure allows the system to return objects containing the necessary course data that the front-end team can display.

**Comment by nelson-escalona** [comment]
Looks good to me! 👍
