### ISSUE TITLE
Create functions to get and update the classes in the semesters in the college planning feature.

### ISSUE THREAD

**Issue by nelson-escalona** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#94]
Objective:
Create all the functions necessary to get and update the classes in the semesters in the college planning feature.

Description:
This task involves creating the necessary functions to get the courses to a specific semester from the database. These functions must return a list of 'course' objects given the students data and the semester to get the courser from.

Research must me conducted on the database design to check the necessary queries.

The scope of this issue is to deal with adding, deleting and updating courses to the planned semesters. Dealing with the actual planning semesters(creating, updating, deleting semesters) is NOT in the scope of this issue.

Requirements:
For this task, the semester and courses classes must be completed.

Time Constraints:
No time constraint yet. But will be updated.

Completion Criteria:
We have fully functional functions that given student data and a specific semester, they return the classes in that semester.

Difficulty: 3

Priority: 4

Assignees: No assignees yet

NOTE: Task created to avoid further point decay. More information on the task coming later.

**Comment by nelson-escalona** [comment]
Added "The scope of this issue is to deal with adding, deleting, and updating courses to the planned semesters. Dealing with the actual planning semesters(creating, updating, deleting semesters) is NOT in the scope of this issue." to the issue description to better clarify this issue and define the difference between this issue and issue #96.

**Comment by Jeanpaul-Ortiz** [comment]
These three functions were added to manage courses in SemesterPlanning planned_courses to insert, update or delete courses. Extra steps were take to ensure changes are synchronized between the in-memory planned_courses list and the database:

**### _insert_course:**

Checks if a course is already in the planned_courses list.
If not present, adds the course to the list and immediately updates the database using the update method.
Prevents duplicates by performing the check before insertion.

The differentiation from the _insert_courses from issue #96  , is that my function manages the planned_courses list and then updates the database, making sure the course is not already in the list, its most optimal when the SemesterPlanning object has already been created. The _insert_courses directly deals with the database, making it more optimal for the creation of the SemesterPlanning object.

**### update_course:**
Finds a course by its code in the planned_courses list.
If found, replaces the existing course with the new one provided.
Calls the update method to synchronize the change with the database.

**### delete_course:**
Verifies if the course exists in the planned_courses list before proceeding.
Removes the course from the list if it exists and then updates the database using the update method.


These functions keep the planned_courses list and database consistent by leveraging the update function to handle all database changes after modifications.

<img width="1046" alt="Screenshot 2024-10-25 at 8 32 16 PM" src="https://github.com/user-attachments/assets/74ef9f6d-8942-4084-93b7-43af15c8b27d">

**Comment by nelson-escalona** [comment]
LGTM👍
