### ISSUE TITLE
Summarize professor’s feedback on Milestone 1 documentation

### ISSUE THREAD

**Issue by nicolle-feliciano** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#95]
Objective:
Summarize the feedback provided by the professor on the Milestone 1 documentation.

Description:
The professor’s feedback on the Milestone 1 documentation must be summarized. This summary will highlight areas for improvement and any specific suggestions made by the professor. The goal is to create a clear overview that will be used to make any necessary adjustments and improvements to the documentation of Milestone 2.

Requirements:
* Create a concise summary that highlights key points.
* Ensure the summary is easily understandable by team members for implementation.

Time Constraints:
October 9

Completion Criteria:
The summary captures key points from the professor’s feedback and is ready for team review.

Difficulty:
2

Priority:
4

Suggested number of Assignees:
1

**Comment by Ar2691** [comment]
@michellebou
