### ISSUE TITLE
Create CRUD Functions for Semester Planning Table

### ISSUE THREAD

**Issue by carlospepin23** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#96]
## Objective:
Implement CRUD functions for the `semester_planning` table.

## Description:
This task involves creating the necessary CRUD functions for the `semester_planning` table. These functions will allow users to manage semester planning data efficiently within the application.

## Requirements:

- Implement Create, Read, Update, and Delete functions for the `semester_planning` table.
- Ensure the functions validate data and handle errors appropriately.
- Maintain existing database relationships while integrating the new CRUD functionality.

## Time Constraints:
Complete by Friday, **October 18.**

## Completion Criteria:
CRUD functionality for the `semester_planning` table is implemented and integrated with the Semester Planning class.

### Difficulty: **4**
The task involves understanding existing database relationships and creating functions that interact with the `semester_planning `table.

### Priority: **3**
This task is important for the Semester Planning feature; however, it has a priority of 3 since there is sufficient time, and it will be worked on after the Semester Planning class is created.

## Recommended Assignees:
**1x** Developer

## Database Table:
![image](https://github.com/user-attachments/assets/e26bc6a5-51dc-432b-b067-3b126dc698bd)

**Comment by carlospepin23** [comment]
Completed fully functional CRUD operations for the Semester Planning class and separated the database connection into a different file, which is imported into `SemesterPlanning.py`.

Waiting for Team Leader @nelson-escalona approval.

**Comment by nelson-escalona** [comment]
LGTM 👍
