### ISSUE TITLE
Create Semester Planning Class

### ISSUE THREAD

**Issue by carlospepin23** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#97]
## Objective:
Develop an object-oriented class for managing semester planning functionalities within the application.

## Description:
This task involves creating a Semester Planning class that encapsulates the properties and behaviors related to semester planning, which will later be integrated with the CRUD functions for the `semester_planning` table.

## Requirements:
- Implement a Semester Planning class that includes properties such as `planning_id`, `student_id`, `semester_name` and `planned courses.`

## Time Constraints:
Complete by Tuesday, October 15.

## Completion Criteria:
A fully functional Semester Planning class is implemented, enabling effective management of semester planning data.

### Difficulty: **3**
This task requires understanding of object-oriented programming principles.

### Priority: **4**
This task has a priority of 4 because the Semester Planning class must be created before the CRUD functions can be implemented.

## Recommended Assignees:
1x Developer

## Database Table:

![image](https://github.com/user-attachments/assets/e26bc6a5-51dc-432b-b067-3b126dc698bd)

**Comment by carlospepin23** [comment]
I have successfully implemented the `SemesterPlanning` class as specified. It includes the required properties such as `planning_id`, `student_id`, `semester_name`, and a list to manage the `planned courses`. Everything can be reviewed in the linked branch. This foundation is now ready for integration with the CRUD operations for the semester_planning table.

**Comment by nelson-escalona** [comment]
LGTM 👍
