### ISSUE TITLE
Implementation of "Forgot Password" functionality with different recovery methods

### ISSUE THREAD

**Issue by RayMuvz** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#99]
### **Objective**:

Implement the "Forgot Password" feature in the Login screen so that users can recover their password or reset their current one.

### **Description**: 

This task will focus on creating a "Forgot Password" option that allows users to request a password reset via email (or alternate methods), generating a temporary token for secure access. As the leader, you’ll ensure that the recovery process is seamless and secure, overseeing the generation, use, and expiration of these tokens to maintain system security.

### **Features**:

1. "Forgot Password" Button on Login Screen

Add a clickable "Forgot Password?" text or button below the login form. When clicked, it opens a new form that allows users to enter their registered email or username to request a password reset.

2. Email Input Form for Password Recovery

A form asking the user to input their email (or an alternate identifier like username). We will validate the email format and ensure the entered email exists in the database before proceeding.

3. Token Generation for Password Reset

Upon a valid request, generate a secure temporary token (a unique string of characters) that links to the password reset page. Token is randomized and time-bound (e.g., expires in 15 minutes).

4. Email Notification with Password Reset Link

Automatically send an email containing the password reset link to the user. The link should include the unique token. This personalized email should include: 

- Instructions to reset the password.

- A clear expiry notice for the reset link.

- Encouragement for users to contact support if they didn't request the reset.

5. Password Reset Form

A form where users input a new password after clicking the link in their email. This form should include the following fields:

- New Password field (with strength requirements like length, special characters, etc.).

- Confirm New Password field.

**Ensure both password fields match and adhere to security requirements (e.g., length, complexity).**

6. Token Verification and Expiration Handling

Validate the token when the user opens the reset link and check if the token exists. If it exists and has expired, invalidate the token after use to prevent reuse.

This system should display an error message if the token is invalid or expired, with a link to request a new token.

7. Reset Password Confirmation

After a successful password reset, notify the user via: 

- A confirmation page or message that says "Password reset successful."

- A follow-up email notifying the user of the password reset. This also helps if the reset was done by an attacker, so the user can act quickly.

8. Captcha or Two-Factor Authentication 

Add additional layers of security by requiring users to complete a CAPTCHA before sending a reset request. Implement a two-factor authentication for high-security systems, where users need to verify via SMS or an authentication app after clicking the reset link.

9. Temporary Lockout for Multiple Failed Attempts (Optional)

Implement a system that temporarily locks out the "Forgot Password" functionality for users who submit too many incorrect requests within a short time frame.

### **Difficulty:**
6 (Not too difficult to implement, but it requires A LOT of features. May be a little time-consuming).

### **Priority:**
5 (Not too important for the time being, however it is important that this feature exist for Milestone 3).

**Comment by RayMuvz** [comment]
### Process of Password Reset:

1. **Click "Forgot Password" button**
![image](https://github.com/user-attachments/assets/585c1e3e-f417-414a-8aa0-8dafc4f2e22e)

2. **Enter user email for validation with database**
![image](https://github.com/user-attachments/assets/6ff3e895-c0c7-42c4-b4d5-a1c1723341ac)
![image](https://github.com/user-attachments/assets/a9a9fc1e-fff5-412e-b306-1561d391e7c5)

3. **Enter the one time token sent to email**
![image](https://github.com/user-attachments/assets/02ce486e-872d-4834-b38e-79c34362b641)
![image](https://github.com/user-attachments/assets/cd7f84da-f217-43f7-8f10-d648554349b7)


4. **Validate token to reset password**
![image](https://github.com/user-attachments/assets/157b18a1-56e9-4c69-98d7-183a10eed8f2)

5. **Reset Password**
![image](https://github.com/user-attachments/assets/2f6a8b45-cb93-4dc4-be88-ccaa61457bc6)

**Comment by Ar2691** [comment]
This task was broken into smaller tasks, therefore this would be duplicate. Recommended to move it to discussion or the developers closing it.
